"""Naming and tag conventions for cardinal CloudFormation resources.

The prefix policy is `cardinal-` primary, `chq-` only when an AWS resource
length cap forces it. By default we use `cardinal-` everywhere. Resource
physical names are auto-generated by CloudFormation; the human-readable
label lives in the Name tag.

InstallIdShort and InstallIdLong are template parameters set by the root
and threaded into every nested child. These helpers reference them via
Sub strings, so any consumer must declare both as parameters.
"""

from troposphere import Sub, Tags


CARDINAL_PROJECT_TAG = "cardinal"
MANAGED_BY_TAG = "cardinal-cfn"


def cardinal_tags(*, component: str, role: str) -> Tags:
    """Standard tag set for any cardinal resource.

    component: subsystem (e.g. "storage", "compute", "database")
    role:      human-readable role within the subsystem (e.g. "ingest-bucket")
    """
    return Tags(
        Name=Sub(f"cardinal-{role}-${{InstallIdShort}}"),
        Project=CARDINAL_PROJECT_TAG,
        Component=component,
        ManagedBy=MANAGED_BY_TAG,
    )


def name_tag(*, role: str):
    """Sub-string for resources that accept a single Name attribute (not Tags)."""
    return Sub(f"cardinal-{role}-${{InstallIdShort}}")


def ssm_param_name(*, key: str):
    """Explicit SSM parameter name. AWS requires Name on SSM parameters."""
    return Sub(f"cardinal/${{InstallIdLong}}/{key}")


def secret_name(*, purpose: str):
    """Explicit Secrets Manager Secret name (only for externally-referenced secrets)."""
    return Sub(f"cardinal/${{InstallIdLong}}/{purpose}")
