#!/bin/sh
# Build the single-file, self-contained per-stack deploy drivers in scripts/
# from the parts in scripts-src/parts/.  Each driver is a front-half fragment
# (parts/<name>.sh) concatenated with the embedded engine (parts/base.sh) into
# one runnable file, so a customer only ever copies a single script.
#
# Run via `make scripts` (also invoked by the top-level build.sh).  The
# generated drivers are committed; tests/unit/test_deploy_stack_lint.py asserts
# they match a fresh build, so regenerate and commit after editing any part.

set -eu

src_dir=$(cd -- "$(dirname -- "$0")" >/dev/null 2>&1 && pwd)
parts_dir="$src_dir/parts"
# OUT_DIR overrides the destination (the drift test builds into a temp dir);
# default is the customer-facing scripts/ at the repo root.
out_dir="${OUT_DIR:-$(cd -- "$src_dir/.." >/dev/null 2>&1 && pwd)/scripts}"

base="$parts_dir/base.sh"
[ -r "$base" ] || { echo "build.sh: missing engine part: $base" >&2; exit 1; }

for fragment in "$parts_dir"/*.sh; do
    name=$(basename "$fragment")
    [ "$name" = "base.sh" ] && continue
    out="$out_dir/$name"
    {
        printf '#!/bin/sh\n'
        printf '# GENERATED by `make scripts` from scripts-src/parts/%s + parts/base.sh -- edits here are overwritten on regenerate.\n' "$name"
        tail -n +2 "$fragment"
        printf '\n# --- embedded engine (scripts-src/parts/base.sh) ---\n'
        tail -n +2 "$base"
    } >"$out"
    chmod +x "$out"
    echo "wrote $out"
done
