#!/bin/sh
# GENERATED by `make scripts` from scripts-src/parts/deploy-satellite-services.sh + parts/base.sh -- edits here are overwritten on regenerate.
# Jenkins job 4: deploy the cardinal-satellite-services stack (the same-account
# otel collector that performs ingest into the satellite raw bucket/queue).
#
# Upstream: only the satellite's OWN paired stack (same account/region):
#   - satellite-infra-base : RawBucketName output -> RawBucketName param.
# The output name matches the parameter name, so a plain FROM_STACKS pull wires
# it up.  No pull from the central lakerunner-infra-base stack -- the collector
# needs no license and a satellite may live in a different account.
# OTEL_REPLICAS defaults to 1 here (the collector config must change before
# scaling past one replica -- see docs/operations/jenkins-chained-deploy.md).
#
# Self-contained single-file driver: this front-half sets the engine env, then
# falls through into the engine embedded below by scripts-src/build.sh (do not
# edit the generated copy).  Pure environment-variable interface (no flags).

set -eu

DEFAULT_TEMPLATE_BASE_URL="https://cardinal-cfn-us-east-1.s3.us-east-1.amazonaws.com/lakerunner"
TEMPLATE_KEY="cardinal-satellite-services.yaml"

usage() {
    cat <<EOF
deploy-satellite-services.sh -- deploy the cardinal-satellite-services stack.

All inputs come from environment variables (no flags).

Required:
  STACK_NAME                  Stack to create/update.
  REGION                      AWS region (never defaulted; must be set explicitly).
  VERSION                     Published template tag.
  SATELLITE_INFRA_BASE_STACK  Upstream satellite-infra-base (RawBucketName).
  ORGANIZATION_ID             Org UUID this satellite's telemetry is attributed to.
  VPC_ID                      VPC for the collector.
  ALB_SUBNETS                 Comma-separated subnets for the collector ALB.
  TASK_SUBNETS                Comma-separated subnets for the collector tasks.
  ECS_CLUSTER_ARN             ECS cluster for the collector.

Optional (template defaults preserved when unset):
  ALB_SCHEME           internet-facing | internal (default internal).
  INGEST_SOURCE_CIDR   Allowed source CIDR for the collector ALB (template default 10.0.0.0/8).
  OTEL_REPLICAS        Collector replica count (default 1; >1 requires a
                       collector config change first).
  TEMPLATE_BASE_URL    Default: $DEFAULT_TEMPLATE_BASE_URL
  DEPLOYER_ROLE_ARN    Passed to create-change-set.
  NO_EXECUTE           Non-empty: change-set only, do not execute.
EOF
}

case "${1:-}" in
    -h|--help) usage; exit 0 ;;
    "") : ;;
    *) echo "[deploy-satellite-services] ERROR: this script takes no arguments; configure it via environment variables" >&2; usage >&2; exit 2 ;;
esac

# Echo the inputs this script can actually see before validating, so a
# "missing required" failure is easy to diagnose.  The usual cause is a value
# set as a plain shell variable but not exported -- this child process then
# never receives it, and it shows as <unset> below.
echo "[deploy-satellite-services] inputs visible to this process:" >&2
for _v in STACK_NAME REGION VERSION SATELLITE_INFRA_BASE_STACK ORGANIZATION_ID \
          VPC_ID ALB_SUBNETS TASK_SUBNETS ECS_CLUSTER_ARN \
          ALB_SCHEME INGEST_SOURCE_CIDR OTEL_REPLICAS TEMPLATE_BASE_URL \
          DEPLOYER_ROLE_ARN NO_EXECUTE; do
    eval "_val=\${$_v:-}"
    printf '[deploy-satellite-services]   %-27s = %s\n' "$_v" "${_val:-<unset>}" >&2
done

missing=""
[ -z "${STACK_NAME:-}" ] && missing="$missing STACK_NAME"
[ -z "${REGION:-}" ] && missing="$missing REGION"
[ -z "${VERSION:-}" ] && missing="$missing VERSION"
[ -z "${SATELLITE_INFRA_BASE_STACK:-}" ] && missing="$missing SATELLITE_INFRA_BASE_STACK"
[ -z "${ORGANIZATION_ID:-}" ] && missing="$missing ORGANIZATION_ID"
[ -z "${VPC_ID:-}" ] && missing="$missing VPC_ID"
[ -z "${ALB_SUBNETS:-}" ] && missing="$missing ALB_SUBNETS"
[ -z "${TASK_SUBNETS:-}" ] && missing="$missing TASK_SUBNETS"
[ -z "${ECS_CLUSTER_ARN:-}" ] && missing="$missing ECS_CLUSTER_ARN"
if [ -n "$missing" ]; then
    usage >&2
    echo "[deploy-satellite-services] ERROR: missing required: $(echo "$missing" | sed 's/^ //; s/ /, /g')" >&2
    exit 2
fi

template_base_url="${TEMPLATE_BASE_URL:-$DEFAULT_TEMPLATE_BASE_URL}"

# OTEL_REPLICAS defaults to 1 here (single replica; >1 needs a collector config
# change first).  Always passed so the wrapper default, not the template
# default, governs.
otel_replicas="${OTEL_REPLICAS:-1}"

TEMPLATE_URL="$template_base_url/$VERSION/$TEMPLATE_KEY"
FROM_STACKS="$SATELLITE_INFRA_BASE_STACK"
MAPS=""

params="OrganizationId=$ORGANIZATION_ID
VpcId=$VPC_ID
AlbSubnetsCsv=$ALB_SUBNETS
TaskSubnetsCsv=$TASK_SUBNETS
EcsClusterArn=$ECS_CLUSTER_ARN
OtelReplicas=$otel_replicas"
[ -n "${ALB_SCHEME:-}" ] && params="$params
AlbScheme=$ALB_SCHEME"
[ -n "${INGEST_SOURCE_CIDR:-}" ] && params="$params
IngestSourceCidr=$INGEST_SOURCE_CIDR"

PARAMS="$params"

export TEMPLATE_URL PARAMS FROM_STACKS MAPS

# --- embedded engine (scripts-src/parts/base.sh) ---
# Generic chained CloudFormation deploy driver for the 5-stack satellite-ingest
# topology.  Create the stack if missing, otherwise update it in place, pulling
# parameter values from upstream stacks' Outputs so the per-stack Jenkins jobs
# can run as a chain.
#
# Self-contained: depends only on a POSIX shell, the AWS CLI v2, and jq.  Does
# not depend on the cardinal_cfn Python package.
#
# Pure environment-variable interface (no flags).  Inputs:
#
#   Required:
#     STACK_NAME     Stack to create or upgrade.
#     TEMPLATE_URL   S3 URL of the generated template.
#     REGION         AWS region (never defaulted -- a wrong region is hard to
#                    undo, so it must be set explicitly).
#
#   Optional:
#     FROM_STACKS        Space-separated upstream stack names.  An Output whose
#                        key equals a target parameter name supplies it.
#     PARAMS             Newline-separated Key=Value parameter overrides
#                        (highest precedence).  Newline-separated, not
#                        semicolon-separated, so values that contain semicolons
#                        (e.g. some ARNs/URLs) are passed intact.
#     MAPS               Newline-separated TargetParam=SourceOutputKey entries.
#     DEPLOYER_ROLE_ARN  Passed via --role-arn to create-change-set.
#     NO_EXECUTE         Non-empty: create and describe the change set, then stop.
#
# Mode is auto-detected from describe-stacks: missing stack -> CREATE,
# existing stack -> UPDATE.
#
# Per-parameter resolution precedence (from the target template's
# get-template-summary Parameters list):
#   1. PARAMS Key=Value           explicit override (highest precedence)
#   2. MAPS TargetParam=SrcKey    value of an upstream Output named SrcKey
#   3. FROM_STACKS output         an upstream Output whose key == the param name
#   4. UPDATE only: UsePreviousValue:true (carry the current stack value)
#   5. the template's Default
#   6. otherwise FAIL, listing the unresolved required parameters
#
# See docs/operations/jenkins-chained-deploy.md for operator documentation and
# the per-stack wrappers (deploy-lakerunner-infra-base.sh, etc.).

set -eu

CHANGE_SET_PREFIX="cardinal-deploy-"

stack_name="${STACK_NAME:-}"
template_url="${TEMPLATE_URL:-}"
region="${REGION:-}"
deployer_role_arn="${DEPLOYER_ROLE_ARN:-}"
no_execute=""
[ -n "${NO_EXECUTE:-}" ] && no_execute="true"

# Repeatable collections, stored newline-delimited in shell variables.
from_stacks=""      # one stack name per line
param_overrides=""  # one Key=Value per line
file_params=""      # one ParamName=/path/to/file per line
maps=""             # one TargetParam=SourceOutputKey per line

# FROM_STACKS is space-separated on input; normalize to one stack name per line.
if [ -n "${FROM_STACKS:-}" ]; then
    for sname in $FROM_STACKS; do
        from_stacks="${from_stacks}${sname}
"
    done
fi
# PARAMS, FILE_PARAMS, and MAPS are already newline-separated on input.
[ -n "${PARAMS:-}" ] && param_overrides="$PARAMS"
[ -n "${FILE_PARAMS:-}" ] && file_params="$FILE_PARAMS"
[ -n "${MAPS:-}" ] && maps="$MAPS"

# Internal test hook state: resolve parameters from local JSON fixtures and
# print the resolved list, without touching AWS.  Engaged only via the
# positional --internal-resolve-params hook in main(); not an env-var input.
internal_resolve_summary=""
internal_resolve_upstream=""
internal_resolve_current=""

# State held across stages so the abort handler can clean up.
change_set_name=""
work_dir=""

usage() {
    cat <<'EOF'
deploy-stack.sh -- generic chained CloudFormation deploy driver.

All inputs come from environment variables (no flags).

Required:
  STACK_NAME      Stack to create or upgrade.
  TEMPLATE_URL    S3 URL of the generated template.
  REGION          AWS region (never defaulted; must be set explicitly).

Optional:
  FROM_STACKS         Space-separated upstream stack names; an Output whose key
                      equals a target parameter name supplies that parameter.
  PARAMS              Newline-separated Key=Value parameter overrides (highest
                      precedence).  Newline- (not semicolon-) separated so that
                      values containing semicolons are safe.
  FILE_PARAMS         Newline-separated ParamName=/path/to/file entries.  Each
                      file's full content (multi-line/PEM safe) becomes that
                      parameter's value.  Same explicit-override tier as PARAMS;
                      if both set the same parameter, PARAMS wins.
  MAPS                Newline-separated TargetParam=SourceOutputKey entries.
  DEPLOYER_ROLE_ARN   Passed via --role-arn to create-change-set.
  NO_EXECUTE          Non-empty: create and describe the change set, then stop.

Exit codes:
  0  success or no-op
  1  generic / AWS / change set failure
  2  pre-flight / input validation failure
EOF
}

log() {
    printf '[%s] %s\n' "deploy-stack" "$*" >&2
}

fail() {
    code="$1"
    shift
    printf '[deploy-stack] ERROR: %s\n' "$*" >&2
    exit "$code"
}

# ---------------------------------------------------------------------------
# Pure parameter resolver.  Reads three JSON files:
#   summary_file  : the target template's get-template-summary Parameters array
#   upstream_file : a JSON object {ParamName: Value} of all candidate upstream
#                   values (from FROM_STACKS outputs, MAPS'd outputs, and
#                   PARAMS overrides), already merged in precedence order by
#                   the caller (later wins).  An object key present here is a
#                   resolved value.
#   current_file  : the current stack's Parameters array (UPDATE) or [] (CREATE)
# mode is "create" or "update".
# Prints the resolved CloudFormation --parameters list to stdout.
# ---------------------------------------------------------------------------
resolve_params() {
    summary_file="$1"
    upstream_file="$2"
    current_file="$3"
    mode="$4"

    if [ ! -r "$summary_file" ]; then
        fail 2 "cannot read template-summary file: $summary_file"
    fi
    if [ ! -r "$upstream_file" ]; then
        fail 2 "cannot read upstream-values file: $upstream_file"
    fi
    if [ ! -r "$current_file" ]; then
        fail 2 "cannot read current-stack-params file: $current_file"
    fi

    resolved=$(jq -nc \
        --slurpfile sum "$summary_file" \
        --slurpfile up "$upstream_file" \
        --slurpfile cur "$current_file" \
        --arg mode "$mode" \
        '
        ($sum[0] // []) as $params
        | ($up[0] // {}) as $upstream
        | ($cur[0] // []) as $current
        | ($current | map({(.ParameterKey): .ParameterValue}) | add // {}) as $current_by_key
        | $params
        | map(
            . as $p
            | $p.ParameterKey as $k
            | ($upstream | has($k)) as $rule_upstream
            | (($mode == "update") and ($current_by_key | has($k))) as $rule_carry
            | (has("DefaultValue")) as $rule_default
            | if $rule_upstream then
                {ParameterKey: $k, ParameterValue: ($upstream[$k] | tostring)}
              elif $rule_carry then
                {ParameterKey: $k, UsePreviousValue: true}
              elif $rule_default then
                {ParameterKey: $k, ParameterValue: $p.DefaultValue}
              else
                {ParameterKey: $k, _missing: true}
              end
          )
        '
    )

    missing=$(printf '%s' "$resolved" | jq -r '[.[] | select(._missing == true) | .ParameterKey] | join(", ")')
    if [ -n "$missing" ]; then
        fail 2 "no value (override, MAPS, upstream output, current value, or default) for required parameter(s): $missing"
    fi

    printf '%s\n' "$resolved" | jq '.'
}

# ---------------------------------------------------------------------------
# Classify a change set status + reason as one of {success, noop, failure}.
# ---------------------------------------------------------------------------
classify_status() {
    status="$1"
    reason="$2"
    case "$status" in
        CREATE_COMPLETE) printf 'success\n'; return 0 ;;
    esac
    case "$reason" in
        *"didn't contain changes"*|*"No updates are to be performed"*)
            printf 'noop\n'; return 0 ;;
    esac
    printf 'failure\n'
    return 0
}

# ---------------------------------------------------------------------------
# Pre-flight tool check.
# ---------------------------------------------------------------------------
preflight() {
    missing=""
    for tool in aws jq; do
        if ! command -v "$tool" >/dev/null 2>&1; then
            missing="$missing $tool"
        fi
    done
    if [ -n "$missing" ]; then
        cat >&2 <<EOF
[deploy-stack] ERROR: required tool(s) not found:$missing
Install hints:
  Debian/Ubuntu : sudo apt-get install -y awscli jq
  Amazon Linux  : sudo yum install -y aws-cli jq
  Alpine        : sudo apk add aws-cli jq
  macOS (brew)  : brew install awscli jq
EOF
        exit 2
    fi
}

# ---------------------------------------------------------------------------
# CFN call wrapper that adds --role-arn when configured.  Only create-change-set
# accepts --role-arn; CFN reuses that role during execute-change-set.  All other
# AWS calls must invoke `aws cloudformation` directly.  The lint test enforces
# this -- keep it that way.
# ---------------------------------------------------------------------------
cfntool() {
    if [ -n "$deployer_role_arn" ]; then
        aws cloudformation "$@" --role-arn "$deployer_role_arn"
    else
        aws cloudformation "$@"
    fi
}

cleanup() {
    rc=$?
    if [ "$rc" -ne 0 ] && [ -n "$change_set_name" ] && [ -n "$stack_name" ] && [ -n "$region" ]; then
        log "cleanup: deleting change set $change_set_name"
        aws cloudformation delete-change-set \
            --stack-name "$stack_name" \
            --change-set-name "$change_set_name" \
            --region "$region" >/dev/null 2>&1 || true
    fi
    if [ -n "$work_dir" ] && [ -d "$work_dir" ]; then
        rm -rf "$work_dir"
    fi
    # cert_dir: optional temp dir created by a generated front-half (the
    # services driver's create-time self-signed cert).  Cleaned here so the
    # single combined script has exactly one trap.  Unset in a standalone
    # engine run -> no-op.
    if [ -n "${cert_dir:-}" ] && [ -d "${cert_dir:-}" ]; then
        rm -rf "$cert_dir"
    fi
    exit "$rc"
}

# Build the merged upstream-values JSON object into "$1", in precedence order
# (lowest first so later assignments win):
#   FROM_STACKS -> MAPS -> FILE_PARAMS -> PARAMS.
# FILE_PARAMS and PARAMS share the explicit-override tier; PARAMS is applied
# last so a literal PARAMS value wins over a FILE_PARAMS file for the same key.
build_upstream_values() {
    out_file="$1"

    merged='{}'

    # 3. FROM_STACKS: every Output keyed by its OutputKey.
    if [ -n "$from_stacks" ]; then
        printf '%s' "$from_stacks" | while IFS= read -r sname; do
            [ -n "$sname" ] || continue
            log "pulling outputs from upstream stack: $sname"
            aws cloudformation describe-stacks \
                --stack-name "$sname" \
                --region "$region" \
                --query 'Stacks[0].Outputs' \
                --output json
            printf '\037'
        done >"$out_file.fromstacks"
        # Each stack's outputs array is separated by a 0x1f byte.  Fold them
        # into one object (later stacks win on key collision).
        merged=$(jq -nc --arg merged "$merged" '
            $merged | fromjson
        ' 2>/dev/null || echo '{}')
        # shellcheck disable=SC2030,SC2031
        merged=$(
            tr '\037' '\n' < "$out_file.fromstacks" \
            | jq -sc --argjson base "$merged" '
                reduce (.[] | select(. != null)) as $arr ($base;
                    . + (($arr // []) | map({(.OutputKey): .OutputValue}) | add // {}))
            '
        )
        rm -f "$out_file.fromstacks"
    fi

    # 2. MAPS TargetParam=SourceOutputKey: resolve SourceOutputKey from the
    #    already-merged from-stack outputs.
    if [ -n "$maps" ]; then
        printf '%s\n' "$maps" | while IFS= read -r entry; do
            [ -n "$entry" ] || continue
            tgt=${entry%%=*}
            src=${entry#*=}
            if [ "$tgt" = "$entry" ] || [ -z "$tgt" ] || [ -z "$src" ]; then
                fail 2 "MAPS expects TargetParam=SourceOutputKey, got: $entry"
            fi
            printf '%s\t%s\n' "$tgt" "$src"
        done >"$out_file.maps"
        merged=$(
            jq -nc --argjson m "$merged" --rawfile maps "$out_file.maps" '
                ($maps | split("\n") | map(select(length > 0)) | map(split("\t"))) as $pairs
                | reduce $pairs[] as $p ($m;
                    ($p[1]) as $src
                    | if ($m | has($src)) then . + {($p[0]): $m[$src]}
                      else error("MAPS source output not found upstream: " + $src + " (for " + $p[0] + ")")
                      end)
            '
        ) || fail 2 "failed resolving MAPS entries (see message above)"
        rm -f "$out_file.maps"
    fi

    # 1b. FILE_PARAMS ParamName=/path/to/file: read each file's full content as
    #     the value via jq --rawfile, so multi-line / PEM material is JSON-escaped
    #     correctly.  Applied before PARAMS so a literal PARAMS value wins.
    if [ -n "$file_params" ]; then
        printf '%s\n' "$file_params" | while IFS= read -r entry; do
            [ -n "$entry" ] || continue
            key=${entry%%=*}
            path=${entry#*=}
            if [ "$key" = "$entry" ] || [ -z "$key" ] || [ -z "$path" ]; then
                fail 2 "FILE_PARAMS expects ParamName=/path/to/file, got: $entry"
            fi
            if [ ! -r "$path" ]; then
                fail 2 "FILE_PARAMS file not readable for $key: $path"
            fi
            printf '%s\t%s\n' "$key" "$path"
        done >"$out_file.fileparams" || exit $?
        while IFS="$(printf '\t')" read -r key path; do
            [ -n "$key" ] || continue
            merged=$(
                jq -nc --argjson m "$merged" --arg key "$key" --rawfile val "$path" '
                    $m + {($key): $val}
                '
            ) || fail 2 "failed reading FILE_PARAMS file for $key: $path"
        done <"$out_file.fileparams"
        rm -f "$out_file.fileparams"
    fi

    # 1. PARAMS Key=Value: highest precedence.
    if [ -n "$param_overrides" ]; then
        printf '%s\n' "$param_overrides" | while IFS= read -r entry; do
            [ -n "$entry" ] || continue
            key=${entry%%=*}
            val=${entry#*=}
            if [ "$key" = "$entry" ] || [ -z "$key" ]; then
                fail 2 "PARAMS expects Key=Value, got: $entry"
            fi
            printf '%s\t%s\n' "$key" "$val"
        done >"$out_file.params"
        merged=$(
            jq -nc --argjson m "$merged" --rawfile params "$out_file.params" '
                ($params | split("\n") | map(select(length > 0)) | map(split("\t"))) as $pairs
                | reduce $pairs[] as $p ($m; . + {($p[0]): ($p[1:] | join("\t"))})
            '
        )
        rm -f "$out_file.params"
    fi

    printf '%s\n' "$merged" >"$out_file"
}

main() {
    # Internal test hook: build the merged upstream-values object from the
    # env (PARAMS/FILE_PARAMS/MAPS) and print it, never touching AWS.  Only
    # valid when FROM_STACKS is empty (FROM_STACKS would require AWS).  Used to
    # unit-test FILE_PARAMS multi-line resolution.
    if [ "${1:-}" = "--internal-build-upstream" ]; then
        if ! command -v jq >/dev/null 2>&1; then
            fail 2 "jq is required for --internal-build-upstream"
        fi
        if [ -n "$from_stacks" ]; then
            fail 2 "--internal-build-upstream cannot be used with FROM_STACKS set"
        fi
        work_dir=$(mktemp -d)
        build_upstream_values "$work_dir/upstream.json"
        cat "$work_dir/upstream.json"
        return 0
    fi

    # Internal test hook: resolve from fixtures only, never touch AWS.  Engaged
    # by the positional --internal-resolve-params SUMMARY UPSTREAM CURRENT form.
    if [ "${1:-}" = "--internal-resolve-params" ]; then
        internal_resolve_summary="$2"
        internal_resolve_upstream="$3"
        internal_resolve_current="$4"
        if ! command -v jq >/dev/null 2>&1; then
            fail 2 "jq is required for --internal-resolve-params"
        fi
        # Mode is inferred from whether the current-params fixture is non-empty.
        mode="create"
        if [ -s "$internal_resolve_current" ] \
            && [ "$(jq 'length' "$internal_resolve_current" 2>/dev/null || echo 0)" != "0" ]; then
            mode="update"
        fi
        resolve_params \
            "$internal_resolve_summary" \
            "$internal_resolve_upstream" \
            "$internal_resolve_current" \
            "$mode"
        return 0
    fi

    preflight

    missing_required=""
    [ -z "$stack_name" ] && missing_required="$missing_required STACK_NAME"
    [ -z "$template_url" ] && missing_required="$missing_required TEMPLATE_URL"
    [ -z "$region" ] && missing_required="$missing_required REGION"
    if [ -n "$missing_required" ]; then
        usage >&2
        fail 2 "missing required: $(echo "$missing_required" | sed 's/^ //; s/ /, /g')"
    fi

    log "checking whether stack $stack_name exists in $region"
    existing_status=$(aws cloudformation describe-stacks \
            --stack-name "$stack_name" \
            --region "$region" \
            --query 'Stacks[0].StackStatus' --output text 2>/dev/null || echo "")
    case "$existing_status" in
        REVIEW_IN_PROGRESS|ROLLBACK_COMPLETE)
            log "found stale $existing_status stack; deleting before CREATE"
            aws cloudformation delete-stack \
                --stack-name "$stack_name" \
                --region "$region" >/dev/null 2>&1 || true
            aws cloudformation wait stack-delete-complete \
                --stack-name "$stack_name" \
                --region "$region" >/dev/null 2>&1 || true
            existing_status=""
            ;;
    esac
    if [ -n "$existing_status" ]; then
        mode="update"
        cs_type="UPDATE"
        wait_target="stack-update-complete"
        target_status="UPDATE_COMPLETE"
    else
        mode="create"
        cs_type="CREATE"
        wait_target="stack-create-complete"
        target_status="CREATE_COMPLETE"
    fi
    log "mode: $mode"

    account_id=$(aws sts get-caller-identity --query Account --output text 2>/dev/null || echo "unknown")
    log "AWS account: $account_id  region: $region  stack: $stack_name"
    log "resolving template: $template_url"

    work_dir=$(mktemp -d)

    log "fetching new template parameter schema via get-template-summary"
    aws cloudformation get-template-summary \
        --template-url "$template_url" \
        --region "$region" \
        --query 'Parameters' \
        --output json >"$work_dir/summary.json"

    log "collecting upstream parameter values"
    build_upstream_values "$work_dir/upstream.json"

    if [ "$mode" = "update" ]; then
        aws cloudformation describe-stacks \
            --stack-name "$stack_name" \
            --region "$region" \
            --query 'Stacks[0].Parameters' \
            --output json >"$work_dir/current.json"
    else
        printf '[]\n' >"$work_dir/current.json"
    fi

    log "resolving parameters (mode=$mode)"
    resolve_params \
        "$work_dir/summary.json" \
        "$work_dir/upstream.json" \
        "$work_dir/current.json" \
        "$mode" \
        >"$work_dir/parameters.json"

    change_set_name="${CHANGE_SET_PREFIX}$(date +%s)"
    log "creating change set: $change_set_name (type=$cs_type)"
    cfntool create-change-set \
        --stack-name "$stack_name" \
        --change-set-name "$change_set_name" \
        --change-set-type "$cs_type" \
        --template-url "$template_url" \
        --parameters "file://$work_dir/parameters.json" \
        --capabilities CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND \
        --region "$region" >/dev/null

    log "waiting for change set to reach a terminal state"
    aws cloudformation wait change-set-create-complete \
        --stack-name "$stack_name" \
        --change-set-name "$change_set_name" \
        --region "$region" >/dev/null 2>&1 || true

    cs_status=$(aws cloudformation describe-change-set \
        --stack-name "$stack_name" \
        --change-set-name "$change_set_name" \
        --region "$region" \
        --query 'Status' --output text)
    cs_reason=$(aws cloudformation describe-change-set \
        --stack-name "$stack_name" \
        --change-set-name "$change_set_name" \
        --region "$region" \
        --query 'StatusReason' --output text 2>/dev/null || echo "")

    classification=$(classify_status "$cs_status" "$cs_reason")
    case "$classification" in
        noop)
            log "change set is a no-op; nothing to apply"
            aws cloudformation delete-change-set \
                --stack-name "$stack_name" \
                --change-set-name "$change_set_name" \
                --region "$region" >/dev/null 2>&1 || true
            change_set_name=""
            return 0
            ;;
        failure)
            fail 1 "change set $change_set_name failed: status=$cs_status reason=$cs_reason"
            ;;
    esac

    log "change set summary:"
    aws cloudformation describe-change-set \
        --stack-name "$stack_name" \
        --change-set-name "$change_set_name" \
        --region "$region" \
        --query 'Changes[*].ResourceChange.{Action:Action,Type:ResourceType,Logical:LogicalResourceId,Replacement:Replacement}' \
        --output table

    if [ "$no_execute" = "true" ]; then
        cs_arn=$(aws cloudformation describe-change-set \
            --stack-name "$stack_name" \
            --change-set-name "$change_set_name" \
            --region "$region" \
            --query 'ChangeSetId' --output text)
        log "NO_EXECUTE set; leaving change set in place"
        log "change set name: $change_set_name"
        log "change set ARN:  $cs_arn"
        change_set_name=""
        return 0
    fi

    log "executing change set"
    aws cloudformation execute-change-set \
        --stack-name "$stack_name" \
        --change-set-name "$change_set_name" \
        --region "$region" >/dev/null

    log "waiting for $wait_target"
    if ! aws cloudformation wait "$wait_target" \
            --stack-name "$stack_name" \
            --region "$region"; then
        final_status=$(aws cloudformation describe-stacks \
            --stack-name "$stack_name" \
            --region "$region" \
            --query 'Stacks[0].StackStatus' --output text)
        fail 1 "stack did not reach $target_status; final status: $final_status"
    fi

    change_set_name=""

    log "stack outputs:"
    aws cloudformation describe-stacks \
        --stack-name "$stack_name" \
        --region "$region" \
        --query 'Stacks[0].Outputs' \
        --output table

    log "deploy complete (mode=$mode)"
    return 0
}

# -h/--help short-circuit before the env-var path.
case "${1:-}" in
    -h|--help) usage; exit 0 ;;
esac

trap cleanup EXIT INT TERM HUP

main "$@"
