#!/bin/sh
# GENERATED by `make scripts` from scripts-src/parts/deploy-lakerunner-services.sh + parts/base.sh -- edits here are overwritten on regenerate.
# Jenkins job 5: deploy the cardinal-lakerunner-services stack (the application
# tier: query, process, control, maestro).
#
# Upstream:
#   - lakerunner-infra-base : roles, security groups, secrets, SSM param names.
#   - lakerunner-infra-rds  : Db{Endpoint,MasterSecretArn,Name,Port}.
# All of those output names match the template's parameter names, so plain
# FROM_STACKS pulls wire them up.
#
# Special case: QueueUrl and QueueRoleArn are pulled from the satellite-infra-
# base stack outputs (RawQueueUrl / LakerunnerAccessRoleArn) and passed via
# PARAMS lines (highest precedence). The pubsub-sqs container sets them as plain
# SQS_QUEUE_URL / SQS_ROLE_ARN env vars; the region is the stack's own
# AWS::Region, so no QueueRegion param is needed.
#
# Self-contained single-file driver: this front-half sets the engine env, then
# falls through into the engine embedded below by scripts-src/build.sh (do not
# edit the generated copy).  Pure environment-variable interface (no flags).

set -eu

DEFAULT_TEMPLATE_BASE_URL="https://cardinal-cfn-us-east-1.s3.us-east-1.amazonaws.com/lakerunner"
TEMPLATE_KEY="cardinal-lakerunner-services.yaml"

usage() {
    cat <<EOF
deploy-lakerunner-services.sh -- deploy the cardinal-lakerunner-services stack.

All inputs come from environment variables (no flags).

Required:
  STACK_NAME                  Stack to create/update.
  REGION                      AWS region (never defaulted; must be set explicitly).
  VERSION                     Published template tag.
  INFRA_BASE_STACK            Upstream lakerunner-infra-base.
  INFRA_RDS_STACK             Upstream lakerunner-infra-rds.
  SATELLITE_INFRA_BASE_STACK  Source of RawQueueUrl / LakerunnerAccessRoleArn
                              for the QueueUrl / QueueRoleArn params.
  CLUSTER_ARN                 ECS cluster ARN.
  CLUSTER_NAME                ECS cluster name (no upstream output for it).
  VPC_ID                      VPC for the services.
  PRIVATE_SUBNETS             Comma-separated private subnet ids.
  DEX_ADMIN_PASSWORD_HASH     bcrypt hash for the Maestro/DEX admin login.
                              REQUIRED: DEX will not start without it ("no
                              password hash provided") and MaestroService rolls
                              back.

Optional (template defaults preserved when unset):
  CERTIFICATE_ARN             ACM/IAM cert ARN for the Maestro HTTPS listener.
                              If unset, the script auto-generates a self-signed
                              internal cert ON FIRST CREATE only (browsers will
                              warn; fine for internal/test).  Re-runs (UPDATE)
                              keep the existing cert untouched -- no churn.  Set
                              CERTIFICATE_ARN to use a real cert.
  CERTIFICATE_BODY            PEM cert body (string).  Overrides auto-generation
                              (body + private key must be supplied together).
  CERTIFICATE_PRIVATE_KEY     PEM private key (string).
  CERTIFICATE_CHAIN           PEM chain (string, optional).
  CERTIFICATE_BODY_FILE       PEM cert body (path) -- fallback for CERTIFICATE_BODY.
  CERTIFICATE_PRIVATE_KEY_FILE PEM private key (path) -- fallback for CERTIFICATE_PRIVATE_KEY.
  CERTIFICATE_CHAIN_FILE      PEM chain (path) -- fallback for CERTIFICATE_CHAIN.
  DEX_ADMIN_EMAIL             (template default admin@cardinal.local).
  DEX_CLIENT_ID               (template default maestro-ui).
  OIDC_SUPERADMIN_EMAILS      (template default admin@cardinal.local).
  SATELLITE_SERVICES_STACK    Source of CollectorEndpoint for lakerunner self-
                              telemetry (default cardinal-satellite-services).
                              Self-telemetry is on by default: the wrapper reads
                              this stack's CollectorEndpoint output and passes it
                              as SelfTelemetryEndpoint.  If the stack or its
                              CollectorEndpoint output is absent, it warns and
                              leaves self-telemetry off (never blocks the deploy).
  SELF_TELEMETRY_ENDPOINT     Direct OTLP/HTTP endpoint override for self-
                              telemetry (e.g. http://<alb>:4318).  When non-empty,
                              takes precedence over the SATELLITE_SERVICES_STACK
                              pull.
  SERVICE_NAMESPACE_NAME      Cloud Map namespace (template default cardinal.local).
  PUBLIC_SUBNETS              Comma-separated public subnet ids (template default '').
  ALB_SCHEME                  internet-facing | internal (template default:
                              internal).  For internet-facing you must also set
                              PUBLIC_SUBNETS, and the ALB SG internet ingress is
                              enabled on the infra-base stack (its ALB_SCHEME /
                              ALB_ALLOWED_CIDR* settings).
  LAKERUNNER_IMAGE, MAESTRO_IMAGE, OTEL_IMAGE, DEX_IMAGE, DEX_INIT_IMAGE,
  DB_INIT_IMAGE               Image overrides (template defaults otherwise).
  PUBSUB_AUTOREGISTER         Set to "true" to enable pubsub-sqs auto-
                              registration of satellite buckets (default false).
                              When true, unseen satellite raw-bucket orgs are
                              registered and cooked output is routed to the
                              central instance.
  PUBSUB_AUTOREGISTER_WRITES_TO_INSTANCE
                              Central cooked-bucket instance_num that auto-
                              registered orgs write to (default 1). Required
                              when PUBSUB_AUTOREGISTER=true.
  TEMPLATE_BASE_URL           Default: $DEFAULT_TEMPLATE_BASE_URL.  Also
                              forwarded as the TemplateBaseUrl param (nested
                              children load from the matching prefix).
  DEPLOYER_ROLE_ARN           Passed to create-change-set.
  NO_EXECUTE                  Non-empty: change-set only, do not execute.
EOF
}

case "${1:-}" in
    -h|--help) usage; exit 0 ;;
    "") : ;;
    *) echo "[deploy-lakerunner-services] ERROR: this script takes no arguments; configure it via environment variables" >&2; usage >&2; exit 2 ;;
esac

missing=""
[ -z "${STACK_NAME:-}" ] && missing="$missing STACK_NAME"
[ -z "${REGION:-}" ] && missing="$missing REGION"
[ -z "${VERSION:-}" ] && missing="$missing VERSION"
[ -z "${INFRA_BASE_STACK:-}" ] && missing="$missing INFRA_BASE_STACK"
[ -z "${INFRA_RDS_STACK:-}" ] && missing="$missing INFRA_RDS_STACK"
[ -z "${SATELLITE_INFRA_BASE_STACK:-}" ] && missing="$missing SATELLITE_INFRA_BASE_STACK"
[ -z "${CLUSTER_ARN:-}" ] && missing="$missing CLUSTER_ARN"
[ -z "${CLUSTER_NAME:-}" ] && missing="$missing CLUSTER_NAME"
[ -z "${VPC_ID:-}" ] && missing="$missing VPC_ID"
[ -z "${PRIVATE_SUBNETS:-}" ] && missing="$missing PRIVATE_SUBNETS"
[ -z "${DEX_ADMIN_PASSWORD_HASH:-}" ] && missing="$missing DEX_ADMIN_PASSWORD_HASH"
if [ -n "$missing" ]; then
    usage >&2
    echo "[deploy-lakerunner-services] ERROR: missing required: $(echo "$missing" | sed 's/^ //; s/ /, /g')" >&2
    exit 2
fi

if ! command -v aws >/dev/null 2>&1 || ! command -v jq >/dev/null 2>&1; then
    echo "[deploy-lakerunner-services] ERROR: aws and jq are required" >&2
    exit 2
fi

template_base_url="${TEMPLATE_BASE_URL:-$DEFAULT_TEMPLATE_BASE_URL}"

TEMPLATE_URL="$template_base_url/$VERSION/$TEMPLATE_KEY"

# --- Read QueueUrl / QueueRoleArn from the satellite-infra-base stack. --------
sat_outputs=$(aws cloudformation describe-stacks \
    --stack-name "$SATELLITE_INFRA_BASE_STACK" \
    --region "$REGION" \
    --query 'Stacks[0].Outputs' \
    --output json)

queue_url=$(printf '%s' "$sat_outputs" | jq -r '(.[] | select(.OutputKey == "RawQueueUrl") | .OutputValue) // ""')
role_arn=$(printf '%s' "$sat_outputs" | jq -r '(.[] | select(.OutputKey == "LakerunnerAccessRoleArn") | .OutputValue) // ""')

if [ -z "$queue_url" ] || [ -z "$role_arn" ]; then
    echo "[deploy-lakerunner-services] ERROR: satellite-infra-base stack '$SATELLITE_INFRA_BASE_STACK' is missing one of RawQueueUrl/LakerunnerAccessRoleArn outputs" >&2
    exit 2
fi

# --- Resolve the self-telemetry OTLP/HTTP endpoint. --------------------------
# Self-telemetry is on by default: the lakerunner account always runs a
# satellite collector, so a standard deploy gets data flowing with no extra
# operator config.  A non-empty SELF_TELEMETRY_ENDPOINT override wins; otherwise
# pull the CollectorEndpoint output from SATELLITE_SERVICES_STACK (default
# cardinal-satellite-services).  Resolution is GRACEFUL: a missing stack or a
# missing CollectorEndpoint output warns and leaves self-telemetry off -- it
# must never block the app deploy.
satellite_services_stack="${SATELLITE_SERVICES_STACK:-cardinal-satellite-services}"
self_telemetry_endpoint="${SELF_TELEMETRY_ENDPOINT:-}"
if [ -z "$self_telemetry_endpoint" ]; then
    if sat_services_outputs=$(aws cloudformation describe-stacks \
            --stack-name "$satellite_services_stack" \
            --region "$REGION" \
            --query 'Stacks[0].Outputs' \
            --output json 2>/dev/null); then
        self_telemetry_endpoint=$(printf '%s' "$sat_services_outputs" | jq -r '(.[] | select(.OutputKey == "CollectorEndpoint") | .OutputValue) // ""')
    fi
    if [ -z "$self_telemetry_endpoint" ]; then
        echo "[deploy-lakerunner-services] satellite collector endpoint not found in $satellite_services_stack; self-telemetry disabled" >&2
    fi
fi

# --- Compose the deploy-stack.sh environment. --------------------------------
FROM_STACKS="$INFRA_BASE_STACK $INFRA_RDS_STACK"
MAPS=""

# QueueUrl/QueueRoleArn and TemplateBaseUrl are always set.  TemplateBaseUrl
# must track the version we deploy so nested children load from the matching
# prefix.
params="QueueUrl=$queue_url
QueueRoleArn=$role_arn
TemplateBaseUrl=$template_base_url/$VERSION/cardinal-lakerunner/
ClusterArn=$CLUSTER_ARN
ClusterName=$CLUSTER_NAME
VpcId=$VPC_ID
PrivateSubnets=$PRIVATE_SUBNETS"

[ -n "${PUBLIC_SUBNETS:-}" ] && params="$params
PublicSubnets=$PUBLIC_SUBNETS"
[ -n "${ALB_SCHEME:-}" ] && params="$params
AlbScheme=$ALB_SCHEME"
[ -n "${SERVICE_NAMESPACE_NAME:-}" ] && params="$params
ServiceNamespaceName=$SERVICE_NAMESPACE_NAME"
[ -n "$self_telemetry_endpoint" ] && params="$params
SelfTelemetryEndpoint=$self_telemetry_endpoint"

[ -n "${LAKERUNNER_IMAGE:-}" ] && params="$params
LakerunnerImage=$LAKERUNNER_IMAGE"
[ -n "${MAESTRO_IMAGE:-}" ] && params="$params
MaestroImage=$MAESTRO_IMAGE"
[ -n "${OTEL_IMAGE:-}" ] && params="$params
OtelImage=$OTEL_IMAGE"
[ -n "${DEX_IMAGE:-}" ] && params="$params
DexImage=$DEX_IMAGE"
[ -n "${DEX_INIT_IMAGE:-}" ] && params="$params
DexInitImage=$DEX_INIT_IMAGE"
[ -n "${DB_INIT_IMAGE:-}" ] && params="$params
DbInitImage=$DB_INIT_IMAGE"

# --- Certificate handling. ---------------------------------------------------
# Cert PEM material reaches the template via FILE_PARAMS (multi-line safe), never
# inlined into the newline-delimited PARAMS string.  Operators supply each PEM as
# a direct string env var (CERTIFICATE_BODY / CERTIFICATE_PRIVATE_KEY /
# CERTIFICATE_CHAIN) -- written into a temp dir here -- or as a *_FILE path
# fallback.  The string form wins when both are set.
#
# Create-only auto-generation: the cert.yaml child builds an AWS::IAM::Server-
# Certificate from CertificateBody/CertificatePrivateKey when CertificateArn is
# empty.  A fresh self-signed PEM on every re-run would replace that cert and
# churn the ALB listener, so we generate it ONLY on first create:
#   - CERTIFICATE_ARN set            -> pass it (stable ARN, no churn).
#   - empty + PEM supplied           -> pass the supplied PEMs.
#   - empty + stack absent (CREATE)  -> generate a self-signed cert, pass it.
#   - empty + stack present (UPDATE) -> pass nothing; the engine resolves
#     CertificateBody/CertificatePrivateKey to UsePreviousValue, keeping the
#     existing IAM ServerCertificate untouched.
file_params=""
cert_dir=""
cert_body_path=""
cert_key_path=""
cert_chain_path=""

if [ -n "${CERTIFICATE_ARN:-}" ]; then
    params="$params
CertificateArn=$CERTIFICATE_ARN"
else
    # Resolve each PEM to a file path: the direct string env var (written into a
    # temp dir) wins; the matching *_FILE path is the fallback.
    if [ -n "${CERTIFICATE_BODY:-}" ]; then
        [ -n "$cert_dir" ] || cert_dir=$(mktemp -d)
        printf '%s\n' "$CERTIFICATE_BODY" > "$cert_dir/cert.pem"
        cert_body_path="$cert_dir/cert.pem"
    elif [ -n "${CERTIFICATE_BODY_FILE:-}" ]; then
        [ -r "$CERTIFICATE_BODY_FILE" ] || { echo "[deploy-lakerunner-services] ERROR: cannot read CERTIFICATE_BODY_FILE: $CERTIFICATE_BODY_FILE" >&2; exit 2; }
        cert_body_path="$CERTIFICATE_BODY_FILE"
    fi
    if [ -n "${CERTIFICATE_PRIVATE_KEY:-}" ]; then
        [ -n "$cert_dir" ] || cert_dir=$(mktemp -d)
        printf '%s\n' "$CERTIFICATE_PRIVATE_KEY" > "$cert_dir/key.pem"
        cert_key_path="$cert_dir/key.pem"
    elif [ -n "${CERTIFICATE_PRIVATE_KEY_FILE:-}" ]; then
        [ -r "$CERTIFICATE_PRIVATE_KEY_FILE" ] || { echo "[deploy-lakerunner-services] ERROR: cannot read CERTIFICATE_PRIVATE_KEY_FILE: $CERTIFICATE_PRIVATE_KEY_FILE" >&2; exit 2; }
        cert_key_path="$CERTIFICATE_PRIVATE_KEY_FILE"
    fi
    if [ -n "${CERTIFICATE_CHAIN:-}" ]; then
        [ -n "$cert_dir" ] || cert_dir=$(mktemp -d)
        printf '%s\n' "$CERTIFICATE_CHAIN" > "$cert_dir/chain.pem"
        cert_chain_path="$cert_dir/chain.pem"
    elif [ -n "${CERTIFICATE_CHAIN_FILE:-}" ]; then
        [ -r "$CERTIFICATE_CHAIN_FILE" ] || { echo "[deploy-lakerunner-services] ERROR: cannot read CERTIFICATE_CHAIN_FILE: $CERTIFICATE_CHAIN_FILE" >&2; exit 2; }
        cert_chain_path="$CERTIFICATE_CHAIN_FILE"
    fi

    if [ -n "$cert_body_path" ] || [ -n "$cert_key_path" ]; then
        # Supplied PEM: body and key must come together.
        [ -n "$cert_body_path" ] || { echo "[deploy-lakerunner-services] ERROR: private key supplied without a certificate body (set CERTIFICATE_BODY or CERTIFICATE_BODY_FILE)" >&2; exit 2; }
        [ -n "$cert_key_path" ] || { echo "[deploy-lakerunner-services] ERROR: certificate body supplied without a private key (set CERTIFICATE_PRIVATE_KEY or CERTIFICATE_PRIVATE_KEY_FILE)" >&2; exit 2; }
        file_params="CertificateBody=$cert_body_path
CertificatePrivateKey=$cert_key_path"
        if [ -n "$cert_chain_path" ]; then
            file_params="$file_params
CertificateChain=$cert_chain_path"
        fi
    else
        # No ARN, no PEM.  Generate only on first create (stack absent).
        if aws cloudformation describe-stacks --stack-name "$STACK_NAME" --region "$REGION" >/dev/null 2>&1; then
            echo "[deploy-lakerunner-services] stack exists; keeping the existing self-signed cert (no regeneration)" >&2
        else
            if ! command -v openssl >/dev/null 2>&1; then
                echo "[deploy-lakerunner-services] ERROR: openssl is required to auto-generate a self-signed cert; install openssl or set CERTIFICATE_ARN / CERTIFICATE_BODY+CERTIFICATE_PRIVATE_KEY (or their *_FILE variants)" >&2
                exit 2
            fi
            echo "[deploy-lakerunner-services] no CERTIFICATE_ARN and first create; generating a self-signed internal cert" >&2
            cert_dir=$(mktemp -d)
            if ! openssl req -x509 -newkey rsa:2048 -nodes \
                    -keyout "$cert_dir/key.pem" -out "$cert_dir/cert.pem" \
                    -days 825 -subj "/CN=cardinal.test" \
                    -addext "subjectAltName=DNS:cardinal.test,DNS:*.cardinal.internal" 2>/dev/null; then
                echo "[deploy-lakerunner-services] ERROR: openssl failed to generate the self-signed cert" >&2
                exit 1
            fi
            file_params="CertificateBody=$cert_dir/cert.pem
CertificatePrivateKey=$cert_dir/key.pem"
        fi
    fi
fi

[ -n "${DEX_ADMIN_EMAIL:-}" ] && params="$params
DexAdminEmail=$DEX_ADMIN_EMAIL"
[ -n "${DEX_ADMIN_PASSWORD_HASH:-}" ] && params="$params
DexAdminPasswordHash=$DEX_ADMIN_PASSWORD_HASH"
[ -n "${DEX_CLIENT_ID:-}" ] && params="$params
DexClientId=$DEX_CLIENT_ID"
[ -n "${OIDC_SUPERADMIN_EMAILS:-}" ] && params="$params
OidcSuperadminEmails=$OIDC_SUPERADMIN_EMAILS"

[ -n "${PUBSUB_AUTOREGISTER:-}" ] && params="$params
PubsubAutoRegister=$PUBSUB_AUTOREGISTER"
[ -n "${PUBSUB_AUTOREGISTER_WRITES_TO_INSTANCE:-}" ] && params="$params
PubsubAutoRegisterWritesToInstance=$PUBSUB_AUTOREGISTER_WRITES_TO_INSTANCE"

PARAMS="$params"
FILE_PARAMS="$file_params"

export TEMPLATE_URL PARAMS FILE_PARAMS FROM_STACKS MAPS

# --- embedded engine (scripts-src/parts/base.sh) ---
# Generic chained CloudFormation deploy driver for the 5-stack satellite-ingest
# topology.  Create the stack if missing, otherwise update it in place, pulling
# parameter values from upstream stacks' Outputs so the per-stack Jenkins jobs
# can run as a chain.
#
# Self-contained: depends only on a POSIX shell, the AWS CLI v2, and jq.  Does
# not depend on the cardinal_cfn Python package.
#
# Pure environment-variable interface (no flags).  Inputs:
#
#   Required:
#     STACK_NAME     Stack to create or upgrade.
#     TEMPLATE_URL   S3 URL of the generated template.
#     REGION         AWS region (never defaulted -- a wrong region is hard to
#                    undo, so it must be set explicitly).
#
#   Optional:
#     FROM_STACKS        Space-separated upstream stack names.  An Output whose
#                        key equals a target parameter name supplies it.
#     PARAMS             Newline-separated Key=Value parameter overrides
#                        (highest precedence).  Newline-separated, not
#                        semicolon-separated, so values that contain semicolons
#                        (e.g. some ARNs/URLs) are passed intact.
#     MAPS               Newline-separated TargetParam=SourceOutputKey entries.
#     DEPLOYER_ROLE_ARN  Passed via --role-arn to create-change-set.
#     NO_EXECUTE         Non-empty: create and describe the change set, then stop.
#
# Mode is auto-detected from describe-stacks: missing stack -> CREATE,
# existing stack -> UPDATE.
#
# Per-parameter resolution precedence (from the target template's
# get-template-summary Parameters list):
#   1. PARAMS Key=Value           explicit override (highest precedence)
#   2. MAPS TargetParam=SrcKey    value of an upstream Output named SrcKey
#   3. FROM_STACKS output         an upstream Output whose key == the param name
#   4. UPDATE only: UsePreviousValue:true (carry the current stack value)
#   5. the template's Default
#   6. otherwise FAIL, listing the unresolved required parameters
#
# See docs/operations/jenkins-chained-deploy.md for operator documentation and
# the per-stack wrappers (deploy-lakerunner-infra-base.sh, etc.).

set -eu

CHANGE_SET_PREFIX="cardinal-deploy-"

stack_name="${STACK_NAME:-}"
template_url="${TEMPLATE_URL:-}"
region="${REGION:-}"
deployer_role_arn="${DEPLOYER_ROLE_ARN:-}"
no_execute=""
[ -n "${NO_EXECUTE:-}" ] && no_execute="true"

# Repeatable collections, stored newline-delimited in shell variables.
from_stacks=""      # one stack name per line
param_overrides=""  # one Key=Value per line
file_params=""      # one ParamName=/path/to/file per line
maps=""             # one TargetParam=SourceOutputKey per line

# FROM_STACKS is space-separated on input; normalize to one stack name per line.
if [ -n "${FROM_STACKS:-}" ]; then
    for sname in $FROM_STACKS; do
        from_stacks="${from_stacks}${sname}
"
    done
fi
# PARAMS, FILE_PARAMS, and MAPS are already newline-separated on input.
[ -n "${PARAMS:-}" ] && param_overrides="$PARAMS"
[ -n "${FILE_PARAMS:-}" ] && file_params="$FILE_PARAMS"
[ -n "${MAPS:-}" ] && maps="$MAPS"

# Internal test hook state: resolve parameters from local JSON fixtures and
# print the resolved list, without touching AWS.  Engaged only via the
# positional --internal-resolve-params hook in main(); not an env-var input.
internal_resolve_summary=""
internal_resolve_upstream=""
internal_resolve_current=""

# State held across stages so the abort handler can clean up.
change_set_name=""
work_dir=""

usage() {
    cat <<'EOF'
deploy-stack.sh -- generic chained CloudFormation deploy driver.

All inputs come from environment variables (no flags).

Required:
  STACK_NAME      Stack to create or upgrade.
  TEMPLATE_URL    S3 URL of the generated template.
  REGION          AWS region (never defaulted; must be set explicitly).

Optional:
  FROM_STACKS         Space-separated upstream stack names; an Output whose key
                      equals a target parameter name supplies that parameter.
  PARAMS              Newline-separated Key=Value parameter overrides (highest
                      precedence).  Newline- (not semicolon-) separated so that
                      values containing semicolons are safe.
  FILE_PARAMS         Newline-separated ParamName=/path/to/file entries.  Each
                      file's full content (multi-line/PEM safe) becomes that
                      parameter's value.  Same explicit-override tier as PARAMS;
                      if both set the same parameter, PARAMS wins.
  MAPS                Newline-separated TargetParam=SourceOutputKey entries.
  DEPLOYER_ROLE_ARN   Passed via --role-arn to create-change-set.
  NO_EXECUTE          Non-empty: create and describe the change set, then stop.

Exit codes:
  0  success or no-op
  1  generic / AWS / change set failure
  2  pre-flight / input validation failure
EOF
}

log() {
    printf '[%s] %s\n' "deploy-stack" "$*" >&2
}

fail() {
    code="$1"
    shift
    printf '[deploy-stack] ERROR: %s\n' "$*" >&2
    exit "$code"
}

# ---------------------------------------------------------------------------
# Pure parameter resolver.  Reads three JSON files:
#   summary_file  : the target template's get-template-summary Parameters array
#   upstream_file : a JSON object {ParamName: Value} of all candidate upstream
#                   values (from FROM_STACKS outputs, MAPS'd outputs, and
#                   PARAMS overrides), already merged in precedence order by
#                   the caller (later wins).  An object key present here is a
#                   resolved value.
#   current_file  : the current stack's Parameters array (UPDATE) or [] (CREATE)
# mode is "create" or "update".
# Prints the resolved CloudFormation --parameters list to stdout.
# ---------------------------------------------------------------------------
resolve_params() {
    summary_file="$1"
    upstream_file="$2"
    current_file="$3"
    mode="$4"

    if [ ! -r "$summary_file" ]; then
        fail 2 "cannot read template-summary file: $summary_file"
    fi
    if [ ! -r "$upstream_file" ]; then
        fail 2 "cannot read upstream-values file: $upstream_file"
    fi
    if [ ! -r "$current_file" ]; then
        fail 2 "cannot read current-stack-params file: $current_file"
    fi

    resolved=$(jq -nc \
        --slurpfile sum "$summary_file" \
        --slurpfile up "$upstream_file" \
        --slurpfile cur "$current_file" \
        --arg mode "$mode" \
        '
        ($sum[0] // []) as $params
        | ($up[0] // {}) as $upstream
        | ($cur[0] // []) as $current
        | ($current | map({(.ParameterKey): .ParameterValue}) | add // {}) as $current_by_key
        | $params
        | map(
            . as $p
            | $p.ParameterKey as $k
            | ($upstream | has($k)) as $rule_upstream
            | (($mode == "update") and ($current_by_key | has($k))) as $rule_carry
            | (has("DefaultValue")) as $rule_default
            | if $rule_upstream then
                {ParameterKey: $k, ParameterValue: ($upstream[$k] | tostring)}
              elif $rule_carry then
                {ParameterKey: $k, UsePreviousValue: true}
              elif $rule_default then
                {ParameterKey: $k, ParameterValue: $p.DefaultValue}
              else
                {ParameterKey: $k, _missing: true}
              end
          )
        '
    )

    missing=$(printf '%s' "$resolved" | jq -r '[.[] | select(._missing == true) | .ParameterKey] | join(", ")')
    if [ -n "$missing" ]; then
        fail 2 "no value (override, MAPS, upstream output, current value, or default) for required parameter(s): $missing"
    fi

    printf '%s\n' "$resolved" | jq '.'
}

# ---------------------------------------------------------------------------
# Classify a change set status + reason as one of {success, noop, failure}.
# ---------------------------------------------------------------------------
classify_status() {
    status="$1"
    reason="$2"
    case "$status" in
        CREATE_COMPLETE) printf 'success\n'; return 0 ;;
    esac
    case "$reason" in
        *"didn't contain changes"*|*"No updates are to be performed"*)
            printf 'noop\n'; return 0 ;;
    esac
    printf 'failure\n'
    return 0
}

# ---------------------------------------------------------------------------
# Pre-flight tool check.
# ---------------------------------------------------------------------------
preflight() {
    missing=""
    for tool in aws jq; do
        if ! command -v "$tool" >/dev/null 2>&1; then
            missing="$missing $tool"
        fi
    done
    if [ -n "$missing" ]; then
        cat >&2 <<EOF
[deploy-stack] ERROR: required tool(s) not found:$missing
Install hints:
  Debian/Ubuntu : sudo apt-get install -y awscli jq
  Amazon Linux  : sudo yum install -y aws-cli jq
  Alpine        : sudo apk add aws-cli jq
  macOS (brew)  : brew install awscli jq
EOF
        exit 2
    fi
}

# ---------------------------------------------------------------------------
# CFN call wrapper that adds --role-arn when configured.  Only create-change-set
# accepts --role-arn; CFN reuses that role during execute-change-set.  All other
# AWS calls must invoke `aws cloudformation` directly.  The lint test enforces
# this -- keep it that way.
# ---------------------------------------------------------------------------
cfntool() {
    if [ -n "$deployer_role_arn" ]; then
        aws cloudformation "$@" --role-arn "$deployer_role_arn"
    else
        aws cloudformation "$@"
    fi
}

cleanup() {
    rc=$?
    if [ "$rc" -ne 0 ] && [ -n "$change_set_name" ] && [ -n "$stack_name" ] && [ -n "$region" ]; then
        log "cleanup: deleting change set $change_set_name"
        aws cloudformation delete-change-set \
            --stack-name "$stack_name" \
            --change-set-name "$change_set_name" \
            --region "$region" >/dev/null 2>&1 || true
    fi
    if [ -n "$work_dir" ] && [ -d "$work_dir" ]; then
        rm -rf "$work_dir"
    fi
    # cert_dir: optional temp dir created by a generated front-half (the
    # services driver's create-time self-signed cert).  Cleaned here so the
    # single combined script has exactly one trap.  Unset in a standalone
    # engine run -> no-op.
    if [ -n "${cert_dir:-}" ] && [ -d "${cert_dir:-}" ]; then
        rm -rf "$cert_dir"
    fi
    exit "$rc"
}

# Build the merged upstream-values JSON object into "$1", in precedence order
# (lowest first so later assignments win):
#   FROM_STACKS -> MAPS -> FILE_PARAMS -> PARAMS.
# FILE_PARAMS and PARAMS share the explicit-override tier; PARAMS is applied
# last so a literal PARAMS value wins over a FILE_PARAMS file for the same key.
build_upstream_values() {
    out_file="$1"

    merged='{}'

    # 3. FROM_STACKS: every Output keyed by its OutputKey.
    if [ -n "$from_stacks" ]; then
        printf '%s' "$from_stacks" | while IFS= read -r sname; do
            [ -n "$sname" ] || continue
            log "pulling outputs from upstream stack: $sname"
            aws cloudformation describe-stacks \
                --stack-name "$sname" \
                --region "$region" \
                --query 'Stacks[0].Outputs' \
                --output json
            printf '\037'
        done >"$out_file.fromstacks"
        # Each stack's outputs array is separated by a 0x1f byte.  Fold them
        # into one object (later stacks win on key collision).
        merged=$(jq -nc --arg merged "$merged" '
            $merged | fromjson
        ' 2>/dev/null || echo '{}')
        # shellcheck disable=SC2030,SC2031
        merged=$(
            tr '\037' '\n' < "$out_file.fromstacks" \
            | jq -sc --argjson base "$merged" '
                reduce (.[] | select(. != null)) as $arr ($base;
                    . + (($arr // []) | map({(.OutputKey): .OutputValue}) | add // {}))
            '
        )
        rm -f "$out_file.fromstacks"
    fi

    # 2. MAPS TargetParam=SourceOutputKey: resolve SourceOutputKey from the
    #    already-merged from-stack outputs.
    if [ -n "$maps" ]; then
        printf '%s\n' "$maps" | while IFS= read -r entry; do
            [ -n "$entry" ] || continue
            tgt=${entry%%=*}
            src=${entry#*=}
            if [ "$tgt" = "$entry" ] || [ -z "$tgt" ] || [ -z "$src" ]; then
                fail 2 "MAPS expects TargetParam=SourceOutputKey, got: $entry"
            fi
            printf '%s\t%s\n' "$tgt" "$src"
        done >"$out_file.maps"
        merged=$(
            jq -nc --argjson m "$merged" --rawfile maps "$out_file.maps" '
                ($maps | split("\n") | map(select(length > 0)) | map(split("\t"))) as $pairs
                | reduce $pairs[] as $p ($m;
                    ($p[1]) as $src
                    | if ($m | has($src)) then . + {($p[0]): $m[$src]}
                      else error("MAPS source output not found upstream: " + $src + " (for " + $p[0] + ")")
                      end)
            '
        ) || fail 2 "failed resolving MAPS entries (see message above)"
        rm -f "$out_file.maps"
    fi

    # 1b. FILE_PARAMS ParamName=/path/to/file: read each file's full content as
    #     the value via jq --rawfile, so multi-line / PEM material is JSON-escaped
    #     correctly.  Applied before PARAMS so a literal PARAMS value wins.
    if [ -n "$file_params" ]; then
        printf '%s\n' "$file_params" | while IFS= read -r entry; do
            [ -n "$entry" ] || continue
            key=${entry%%=*}
            path=${entry#*=}
            if [ "$key" = "$entry" ] || [ -z "$key" ] || [ -z "$path" ]; then
                fail 2 "FILE_PARAMS expects ParamName=/path/to/file, got: $entry"
            fi
            if [ ! -r "$path" ]; then
                fail 2 "FILE_PARAMS file not readable for $key: $path"
            fi
            printf '%s\t%s\n' "$key" "$path"
        done >"$out_file.fileparams" || exit $?
        while IFS="$(printf '\t')" read -r key path; do
            [ -n "$key" ] || continue
            merged=$(
                jq -nc --argjson m "$merged" --arg key "$key" --rawfile val "$path" '
                    $m + {($key): $val}
                '
            ) || fail 2 "failed reading FILE_PARAMS file for $key: $path"
        done <"$out_file.fileparams"
        rm -f "$out_file.fileparams"
    fi

    # 1. PARAMS Key=Value: highest precedence.
    if [ -n "$param_overrides" ]; then
        printf '%s\n' "$param_overrides" | while IFS= read -r entry; do
            [ -n "$entry" ] || continue
            key=${entry%%=*}
            val=${entry#*=}
            if [ "$key" = "$entry" ] || [ -z "$key" ]; then
                fail 2 "PARAMS expects Key=Value, got: $entry"
            fi
            printf '%s\t%s\n' "$key" "$val"
        done >"$out_file.params"
        merged=$(
            jq -nc --argjson m "$merged" --rawfile params "$out_file.params" '
                ($params | split("\n") | map(select(length > 0)) | map(split("\t"))) as $pairs
                | reduce $pairs[] as $p ($m; . + {($p[0]): ($p[1:] | join("\t"))})
            '
        )
        rm -f "$out_file.params"
    fi

    printf '%s\n' "$merged" >"$out_file"
}

main() {
    # Internal test hook: build the merged upstream-values object from the
    # env (PARAMS/FILE_PARAMS/MAPS) and print it, never touching AWS.  Only
    # valid when FROM_STACKS is empty (FROM_STACKS would require AWS).  Used to
    # unit-test FILE_PARAMS multi-line resolution.
    if [ "${1:-}" = "--internal-build-upstream" ]; then
        if ! command -v jq >/dev/null 2>&1; then
            fail 2 "jq is required for --internal-build-upstream"
        fi
        if [ -n "$from_stacks" ]; then
            fail 2 "--internal-build-upstream cannot be used with FROM_STACKS set"
        fi
        work_dir=$(mktemp -d)
        build_upstream_values "$work_dir/upstream.json"
        cat "$work_dir/upstream.json"
        return 0
    fi

    # Internal test hook: resolve from fixtures only, never touch AWS.  Engaged
    # by the positional --internal-resolve-params SUMMARY UPSTREAM CURRENT form.
    if [ "${1:-}" = "--internal-resolve-params" ]; then
        internal_resolve_summary="$2"
        internal_resolve_upstream="$3"
        internal_resolve_current="$4"
        if ! command -v jq >/dev/null 2>&1; then
            fail 2 "jq is required for --internal-resolve-params"
        fi
        # Mode is inferred from whether the current-params fixture is non-empty.
        mode="create"
        if [ -s "$internal_resolve_current" ] \
            && [ "$(jq 'length' "$internal_resolve_current" 2>/dev/null || echo 0)" != "0" ]; then
            mode="update"
        fi
        resolve_params \
            "$internal_resolve_summary" \
            "$internal_resolve_upstream" \
            "$internal_resolve_current" \
            "$mode"
        return 0
    fi

    preflight

    missing_required=""
    [ -z "$stack_name" ] && missing_required="$missing_required STACK_NAME"
    [ -z "$template_url" ] && missing_required="$missing_required TEMPLATE_URL"
    [ -z "$region" ] && missing_required="$missing_required REGION"
    if [ -n "$missing_required" ]; then
        usage >&2
        fail 2 "missing required: $(echo "$missing_required" | sed 's/^ //; s/ /, /g')"
    fi

    log "checking whether stack $stack_name exists in $region"
    existing_status=$(aws cloudformation describe-stacks \
            --stack-name "$stack_name" \
            --region "$region" \
            --query 'Stacks[0].StackStatus' --output text 2>/dev/null || echo "")
    case "$existing_status" in
        REVIEW_IN_PROGRESS|ROLLBACK_COMPLETE)
            log "found stale $existing_status stack; deleting before CREATE"
            aws cloudformation delete-stack \
                --stack-name "$stack_name" \
                --region "$region" >/dev/null 2>&1 || true
            aws cloudformation wait stack-delete-complete \
                --stack-name "$stack_name" \
                --region "$region" >/dev/null 2>&1 || true
            existing_status=""
            ;;
    esac
    if [ -n "$existing_status" ]; then
        mode="update"
        cs_type="UPDATE"
        wait_target="stack-update-complete"
        target_status="UPDATE_COMPLETE"
    else
        mode="create"
        cs_type="CREATE"
        wait_target="stack-create-complete"
        target_status="CREATE_COMPLETE"
    fi
    log "mode: $mode"

    account_id=$(aws sts get-caller-identity --query Account --output text 2>/dev/null || echo "unknown")
    log "AWS account: $account_id  region: $region  stack: $stack_name"
    log "resolving template: $template_url"

    work_dir=$(mktemp -d)

    log "fetching new template parameter schema via get-template-summary"
    aws cloudformation get-template-summary \
        --template-url "$template_url" \
        --region "$region" \
        --query 'Parameters' \
        --output json >"$work_dir/summary.json"

    log "collecting upstream parameter values"
    build_upstream_values "$work_dir/upstream.json"

    if [ "$mode" = "update" ]; then
        aws cloudformation describe-stacks \
            --stack-name "$stack_name" \
            --region "$region" \
            --query 'Stacks[0].Parameters' \
            --output json >"$work_dir/current.json"
    else
        printf '[]\n' >"$work_dir/current.json"
    fi

    log "resolving parameters (mode=$mode)"
    resolve_params \
        "$work_dir/summary.json" \
        "$work_dir/upstream.json" \
        "$work_dir/current.json" \
        "$mode" \
        >"$work_dir/parameters.json"

    change_set_name="${CHANGE_SET_PREFIX}$(date +%s)"
    log "creating change set: $change_set_name (type=$cs_type)"
    cfntool create-change-set \
        --stack-name "$stack_name" \
        --change-set-name "$change_set_name" \
        --change-set-type "$cs_type" \
        --template-url "$template_url" \
        --parameters "file://$work_dir/parameters.json" \
        --capabilities CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND \
        --region "$region" >/dev/null

    log "waiting for change set to reach a terminal state"
    aws cloudformation wait change-set-create-complete \
        --stack-name "$stack_name" \
        --change-set-name "$change_set_name" \
        --region "$region" >/dev/null 2>&1 || true

    cs_status=$(aws cloudformation describe-change-set \
        --stack-name "$stack_name" \
        --change-set-name "$change_set_name" \
        --region "$region" \
        --query 'Status' --output text)
    cs_reason=$(aws cloudformation describe-change-set \
        --stack-name "$stack_name" \
        --change-set-name "$change_set_name" \
        --region "$region" \
        --query 'StatusReason' --output text 2>/dev/null || echo "")

    classification=$(classify_status "$cs_status" "$cs_reason")
    case "$classification" in
        noop)
            log "change set is a no-op; nothing to apply"
            aws cloudformation delete-change-set \
                --stack-name "$stack_name" \
                --change-set-name "$change_set_name" \
                --region "$region" >/dev/null 2>&1 || true
            change_set_name=""
            return 0
            ;;
        failure)
            fail 1 "change set $change_set_name failed: status=$cs_status reason=$cs_reason"
            ;;
    esac

    log "change set summary:"
    aws cloudformation describe-change-set \
        --stack-name "$stack_name" \
        --change-set-name "$change_set_name" \
        --region "$region" \
        --query 'Changes[*].ResourceChange.{Action:Action,Type:ResourceType,Logical:LogicalResourceId,Replacement:Replacement}' \
        --output table

    if [ "$no_execute" = "true" ]; then
        cs_arn=$(aws cloudformation describe-change-set \
            --stack-name "$stack_name" \
            --change-set-name "$change_set_name" \
            --region "$region" \
            --query 'ChangeSetId' --output text)
        log "NO_EXECUTE set; leaving change set in place"
        log "change set name: $change_set_name"
        log "change set ARN:  $cs_arn"
        change_set_name=""
        return 0
    fi

    log "executing change set"
    aws cloudformation execute-change-set \
        --stack-name "$stack_name" \
        --change-set-name "$change_set_name" \
        --region "$region" >/dev/null

    log "waiting for $wait_target"
    if ! aws cloudformation wait "$wait_target" \
            --stack-name "$stack_name" \
            --region "$region"; then
        final_status=$(aws cloudformation describe-stacks \
            --stack-name "$stack_name" \
            --region "$region" \
            --query 'Stacks[0].StackStatus' --output text)
        fail 1 "stack did not reach $target_status; final status: $final_status"
    fi

    change_set_name=""

    log "stack outputs:"
    aws cloudformation describe-stacks \
        --stack-name "$stack_name" \
        --region "$region" \
        --query 'Stacks[0].Outputs' \
        --output table

    log "deploy complete (mode=$mode)"
    return 0
}

# -h/--help short-circuit before the env-var path.
case "${1:-}" in
    -h|--help) usage; exit 0 ;;
esac

trap cleanup EXIT INT TERM HUP

main "$@"
