"""Lint tests for the single-file per-stack deploy drivers and the engine part.

The drivers in scripts/ are generated by scripts-src/build.sh, each one a
front-half fragment (scripts-src/parts/<name>.sh) concatenated with the embedded
engine (scripts-src/parts/base.sh).  These tests lint the shipped drivers, lint
the engine part on its own (it stays standalone-runnable for the internal-hook
tests), and assert the committed drivers match a fresh build.

The shellcheck step soft-skips when shellcheck is not on PATH so that
contributors and CI runners without it installed are not blocked.
"""

import json
import os
import shutil
import subprocess
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
SCRIPTS_DIR = REPO_ROOT / "scripts"
PARTS_DIR = REPO_ROOT / "scripts-src" / "parts"
BUILDER = REPO_ROOT / "scripts-src" / "build.sh"

# The engine, embedded into every driver and kept standalone-runnable so the
# internal-hook tests can drive it without AWS.
ENGINE = PARTS_DIR / "base.sh"

# The shipped, self-contained per-stack drivers (one file per stack).
SCRIPTS = [
    SCRIPTS_DIR / "deploy-lakerunner-infra-base.sh",
    SCRIPTS_DIR / "deploy-lakerunner-infra-rds.sh",
    SCRIPTS_DIR / "deploy-satellite-infra-base.sh",
    SCRIPTS_DIR / "deploy-satellite-services.sh",
    SCRIPTS_DIR / "deploy-lakerunner-services.sh",
]

# Syntax + shellcheck cover the drivers and the engine part; the engine is not
# a customer entry point, so the executable/missing-required checks stay on the
# shipped drivers only.
LINTABLE = SCRIPTS + [ENGINE]

# Minimal PATH so a bare invocation reaches the validation branch the same way
# it would on a CI runner.
TEST_PATH = "/usr/bin:/bin:/usr/local/bin:/opt/homebrew/bin"


@pytest.mark.parametrize("script", SCRIPTS, ids=lambda p: p.name)
def test_script_is_executable(script):
    assert script.exists(), f"missing {script}"
    assert script.stat().st_mode & 0o111, f"{script.name} should be executable"


@pytest.mark.parametrize("script", LINTABLE, ids=lambda p: p.name)
def test_syntax_clean(script):
    """`sh -n` must parse the script without errors."""
    result = subprocess.run(
        ["sh", "-n", str(script)],
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, (
        f"sh -n reported a syntax error in {script.name}:\n{result.stderr}"
    )


@pytest.mark.parametrize("script", SCRIPTS, ids=lambda p: p.name)
def test_missing_required_env_prints_usage_and_fails(script):
    """With every required env var cleared, the script should print usage and
    exit non-zero (validation failure), not blow up with a syntax error or
    silently succeed.  The scripts are env-var driven (no flags), so a clean
    env that omits the required vars is the failure path.

    A minimal env (PATH only) clears STACK_NAME/REGION/VERSION/etc. for free.
    """
    result = subprocess.run(
        ["sh", str(script)],
        capture_output=True,
        text=True,
        env={"PATH": TEST_PATH},
    )
    assert result.returncode != 0, (
        f"{script.name} should exit non-zero with required env vars unset, got 0"
    )
    combined = result.stdout + result.stderr
    assert ("REQUIRED" in combined.upper()) or ("missing required" in combined), (
        f"{script.name} should print usage (a REQUIRED section) or a "
        f"'missing required' line to stderr when required env vars are unset:\n"
        f"{combined}"
    )


@pytest.mark.parametrize("script", LINTABLE, ids=lambda p: p.name)
def test_shellcheck_clean(script):
    if shutil.which("shellcheck") is None:
        pytest.skip("shellcheck not installed on this runner")
    result = subprocess.run(
        ["shellcheck", str(script)],
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, (
        f"shellcheck reported issues in {script.name}:\n{result.stdout}\n{result.stderr}"
    )


# ---------------------------------------------------------------------------
# The generic driver wraps only create-change-set in cfntool() (the sole call
# that accepts --role-arn).  Mirrors the guard in test_deploy_lakerunner_lint.
# ---------------------------------------------------------------------------

ALLOWED_CFNTOOL_WRAPPED_SUBCOMMANDS = {"create-change-set"}


def test_cfntool_wrapper_only_wraps_role_capable_subcommands():
    script = ENGINE
    offenders = []
    for i, line in enumerate(script.read_text().splitlines(), 1):
        stripped = line.strip()
        if stripped.startswith("#"):
            continue
        if not stripped.startswith("cfntool "):
            continue
        token = stripped.split()[1] if len(stripped.split()) > 1 else ""
        if not token:
            continue
        if token not in ALLOWED_CFNTOOL_WRAPPED_SUBCOMMANDS:
            offenders.append((i, stripped))
    assert not offenders, (
        "cfntool() wrapper used on subcommand(s) that don't accept --role-arn:\n"
        + "\n".join(f"  {i}: {ln}" for i, ln in offenders)
        + f"\nAllowed: {sorted(ALLOWED_CFNTOOL_WRAPPED_SUBCOMMANDS)}"
    )


def test_satellite_infra_base_maps_lakerunner_principal():
    """The one non-automatic --map: LakerunnerPrincipal <- ProcessRoleArn."""
    text = (SCRIPTS_DIR / "deploy-satellite-infra-base.sh").read_text()
    assert "LakerunnerPrincipal=ProcessRoleArn" in text


def test_lakerunner_services_passes_queue_params():
    """lakerunner-services must read the group-0 queue inputs from the satellite
    outputs and pass them as plain QueueUrl/QueueRoleArn params (no shell blob)."""
    text = (SCRIPTS_DIR / "deploy-lakerunner-services.sh").read_text()
    for token in ("RawQueueUrl", "LakerunnerAccessRoleArn",
                  "QueueUrl=", "QueueRoleArn="):
        assert token in text, f"deploy-lakerunner-services.sh missing {token}"
    assert "PubsubSqsEnv" not in text, "old shell-blob PubsubSqsEnv still present"


def test_lakerunner_services_requires_dex_admin_password_hash():
    """Maestro/DEX will not start without DEX_ADMIN_PASSWORD_HASH, so the
    wrapper must validate it as a REQUIRED env var (collect-all-missing)."""
    text = (SCRIPTS_DIR / "deploy-lakerunner-services.sh").read_text()
    assert 'missing="$missing DEX_ADMIN_PASSWORD_HASH"' in text, (
        "DEX_ADMIN_PASSWORD_HASH is not in the required-vars validation"
    )


def test_lakerunner_services_supports_alb_scheme():
    """The services wrapper forwards an optional ALB_SCHEME -> AlbScheme param,
    mirroring the infra-base wrapper."""
    text = (SCRIPTS_DIR / "deploy-lakerunner-services.sh").read_text()
    assert "AlbScheme=$ALB_SCHEME" in text


def test_infra_base_license_accepts_string_or_file():
    """LICENSE_DATA (direct token string) is the primary input; LICENSE_DATA_FILE
    is kept as a file fallback. One of the two is required."""
    script = SCRIPTS_DIR / "deploy-lakerunner-infra-base.sh"
    text = script.read_text()
    assert 'license_data="$LICENSE_DATA"' in text, "no direct-string license path"
    assert 'cat "$LICENSE_DATA_FILE"' in text, "LICENSE_DATA_FILE fallback dropped"

    # Behavioral: LICENSE_DATA alone satisfies the license requirement.
    with_str = subprocess.run(
        ["sh", str(script)],
        capture_output=True,
        text=True,
        env={"PATH": TEST_PATH, "LICENSE_DATA": "z64:test"},
    )
    miss = [ln for ln in (with_str.stdout + with_str.stderr).splitlines()
            if "missing required" in ln]
    assert miss and "LICENSE_DATA" not in miss[0], (
        f"LICENSE_DATA should satisfy the requirement: {miss}"
    )

    # And with neither var, LICENSE_DATA is reported missing.
    without = subprocess.run(
        ["sh", str(script)], capture_output=True, text=True, env={"PATH": TEST_PATH}
    )
    miss2 = [ln for ln in (without.stdout + without.stderr).splitlines()
             if "missing required" in ln]
    assert miss2 and "LICENSE_DATA" in miss2[0], (
        f"LICENSE_DATA should be required when unset: {miss2}"
    )


def test_services_cert_accepts_string_or_file():
    """Cert PEMs accept a direct string env var (written to a temp dir) with the
    *_FILE path kept as a fallback."""
    text = (SCRIPTS_DIR / "deploy-lakerunner-services.sh").read_text()
    # String PEM -> temp file (then FILE_PARAMS reads it, multi-line safe).
    assert 'cert_body_path="$cert_dir/cert.pem"' in text
    assert '"$CERTIFICATE_BODY"' in text
    # *_FILE fallbacks kept.
    assert 'cert_body_path="$CERTIFICATE_BODY_FILE"' in text
    assert 'cert_key_path="$CERTIFICATE_PRIVATE_KEY_FILE"' in text


def test_lakerunner_services_drops_otel_replicas():
    """The lakerunner-services template no longer has an OtelReplicas param;
    the wrapper must not pass it (dead plumbing)."""
    text = (SCRIPTS_DIR / "deploy-lakerunner-services.sh").read_text()
    assert "OTEL_REPLICAS" not in text
    assert "OtelReplicas" not in text


def test_engine_cleanup_preserves_status_and_clears_cert_dir():
    """The single combined script has exactly one trap -- the engine's
    cleanup().  It must capture $? first (so a FAILED deploy does not false-green
    to 0 via a later command's success), remove the work dir, and remove the
    optional cert temp dir (${cert_dir:-}) that the services front-half creates
    on first create.  The old per-wrapper cleanup_cert trap is gone.
    """
    engine = ENGINE.read_text()
    # Status preserved: captured first, exited with at the end.
    assert "rc=$?" in engine
    assert 'exit "$rc"' in engine
    # The engine owns cert temp dir cleanup so the combined script needs no
    # second trap.
    assert 'rm -rf "$cert_dir"' in engine

    services = (SCRIPTS_DIR / "deploy-lakerunner-services.sh").read_text()
    # The services front-half sets cert_dir; the embedded engine cleans it.
    assert "cert_dir=$(mktemp -d)" in services
    # No competing second trap survived the merge.
    assert "cleanup_cert" not in services
    assert services.count("\ntrap ") == 1, "combined driver must have one trap"

    # Behavioral: the engine's trap idiom propagates a non-zero status.
    harness = (
        "cleanup() { rc=$?; rm -rf /tmp/nonexistent-xyzzy; exit \"$rc\"; }\n"
        "trap cleanup EXIT INT TERM HUP\n"
        "exit 3\n"
    )
    result = subprocess.run(
        ["sh", "-c", harness], capture_output=True, text=True
    )
    assert result.returncode == 3, (
        f"trap idiom must propagate the child's non-zero status, got "
        f"{result.returncode}"
    )


def test_committed_drivers_match_fresh_build(tmp_path):
    """The drivers in scripts/ are generated; assert they are byte-identical to
    a fresh `scripts-src/build.sh` run.  A failure means someone edited a part
    (or a driver) without regenerating -- run `make scripts` and commit."""
    env = dict(os.environ)
    env["OUT_DIR"] = str(tmp_path)
    result = subprocess.run(
        ["sh", str(BUILDER)], capture_output=True, text=True, env=env
    )
    assert result.returncode == 0, (
        f"build.sh failed:\n{result.stdout}\n{result.stderr}"
    )
    for script in SCRIPTS:
        fresh = tmp_path / script.name
        assert fresh.exists(), f"build.sh did not emit {script.name}"
        assert fresh.read_text() == script.read_text(), (
            f"{script.name} is stale; run `make scripts` and commit the result"
        )


def test_resolver_precedence_param_over_upstream(tmp_path):
    """End-to-end of the pure resolver via the internal hook: --param-class
    upstream value wins, a default fills gaps, and an unsatisfied required
    parameter fails."""
    summary = tmp_path / "summary.json"
    summary.write_text(
        '[{"ParameterKey":"A"},'
        '{"ParameterKey":"B","DefaultValue":"bdef"},'
        '{"ParameterKey":"C"}]'
    )
    upstream = tmp_path / "upstream.json"
    upstream.write_text('{"A":"aval"}')
    current = tmp_path / "current.json"
    current.write_text("[]")

    result = subprocess.run(
        [
            "sh",
            str(ENGINE),
            "--internal-resolve-params",
            str(summary),
            str(upstream),
            str(current),
        ],
        capture_output=True,
        text=True,
        env={"PATH": TEST_PATH},
    )
    # C is required and unsatisfied -> exit 2.
    assert result.returncode == 2, (
        f"expected exit 2 for unresolved required param, got "
        f"{result.returncode}:\n{result.stdout}\n{result.stderr}"
    )
    assert "C" in result.stderr


def test_resolver_resolves_when_all_satisfied(tmp_path):
    summary = tmp_path / "summary.json"
    summary.write_text(
        '[{"ParameterKey":"A"},{"ParameterKey":"B","DefaultValue":"bdef"}]'
    )
    upstream = tmp_path / "upstream.json"
    upstream.write_text('{"A":"aval"}')
    current = tmp_path / "current.json"
    current.write_text("[]")

    result = subprocess.run(
        [
            "sh",
            str(ENGINE),
            "--internal-resolve-params",
            str(summary),
            str(upstream),
            str(current),
        ],
        capture_output=True,
        text=True,
        env={"PATH": TEST_PATH},
    )
    assert result.returncode == 0, result.stderr
    assert '"ParameterValue": "aval"' in result.stdout
    assert '"ParameterValue": "bdef"' in result.stdout


# ---------------------------------------------------------------------------
# FILE_PARAMS: a ParamName=/path entry resolves to the file's full (possibly
# multi-line / PEM) content.  Exercised via the --internal-build-upstream hook
# which builds the merged upstream-values object from the env without AWS.
# ---------------------------------------------------------------------------

PEM_CONTENT = (
    "-----BEGIN CERTIFICATE-----\n"
    "line-two-with-special=chars;and:more\n"
    "line-three\n"
    "-----END CERTIFICATE-----\n"
)


def _build_upstream(env_extra):
    env = {"PATH": TEST_PATH}
    env.update(env_extra)
    return subprocess.run(
        ["sh", str(ENGINE), "--internal-build-upstream"],
        capture_output=True,
        text=True,
        env=env,
    )


def test_file_params_resolves_multiline_file_content(tmp_path):
    pem = tmp_path / "cert.pem"
    pem.write_text(PEM_CONTENT)

    result = _build_upstream({"FILE_PARAMS": f"CertificateBody={pem}"})
    assert result.returncode == 0, result.stderr

    merged = json.loads(result.stdout)
    assert merged["CertificateBody"] == PEM_CONTENT, (
        f"FILE_PARAMS value should equal the file content verbatim, got:\n"
        f"{merged.get('CertificateBody')!r}"
    )


def test_file_params_unreadable_file_fails(tmp_path):
    result = _build_upstream(
        {"FILE_PARAMS": f"CertificateBody={tmp_path / 'does-not-exist.pem'}"}
    )
    assert result.returncode == 2, (
        f"expected exit 2 for unreadable FILE_PARAMS file, got "
        f"{result.returncode}:\n{result.stdout}\n{result.stderr}"
    )
    assert "FILE_PARAMS" in result.stderr


def test_params_wins_over_file_params_for_same_key(tmp_path):
    pem = tmp_path / "cert.pem"
    pem.write_text(PEM_CONTENT)

    result = _build_upstream(
        {
            "FILE_PARAMS": f"CertificateBody={pem}",
            "PARAMS": "CertificateBody=literal-wins",
        }
    )
    assert result.returncode == 0, result.stderr
    merged = json.loads(result.stdout)
    assert merged["CertificateBody"] == "literal-wins", (
        "PARAMS should win over FILE_PARAMS for the same key"
    )
