name: Test CloudFormation Templates

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
    
    - name: Create virtual environment
      run: python -m venv .venv
    
    - name: Install dependencies
      run: |
        source .venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        source .venv/bin/activate
        make test
    
    - name: Check templates are up-to-date
      run: |
        source .venv/bin/activate
        make build
        if ! git diff --quiet generated-templates/; then
          echo "ERROR: Generated templates are out of date!"
          echo "Please run 'make build' locally and commit the updated templates."
          echo ""
          echo "Files that changed:"
          git diff --name-only generated-templates/
          echo ""
          echo "Diff:"
          git diff generated-templates/
          exit 1
        fi
        echo "Templates are up-to-date"
    
    - name: Run linting
      run: |
        source .venv/bin/activate
        make lint