Conditions:
  HasApiKeysOverride: !Not
    - !Equals
      - !Ref 'ApiKeysOverride'
      - ''
  HasPublicSubnets: !Not
    - !Equals
      - !Join
        - ','
        - !Ref 'PublicSubnets'
      - ''
  HasStorageProfilesOverride: !Not
    - !Equals
      - !Ref 'StorageProfilesOverride'
      - ''
Description: CommonInfra stack for Lakerunner.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Networking
        Parameters:
          - VpcId
          - PublicSubnets
          - PrivateSubnets
      - Label:
          default: Configuration Overrides (Advanced)
        Parameters:
          - ApiKeysOverride
          - StorageProfilesOverride
    ParameterLabels:
      ApiKeysOverride:
        default: Custom API Keys (YAML)
      PrivateSubnets:
        default: Private Subnets (for ECS/RDS)
      PublicSubnets:
        default: Public Subnets (for ALB internet-facing)
      StorageProfilesOverride:
        default: Custom Storage Profiles (YAML)
      VpcId:
        default: VPC Id
Outputs:
  BucketArn:
    Export:
      Name: !Sub '${AWS::StackName}-BucketArn'
    Value: !GetAtt 'IngestBucket.Arn'
  BucketName:
    Export:
      Name: !Sub '${AWS::StackName}-BucketName'
    Value: !Ref 'IngestBucket'
  ClusterArn:
    Export:
      Name: !Sub '${AWS::StackName}-ClusterArn'
    Value: !GetAtt 'Cluster.Arn'
  DbEndpoint:
    Export:
      Name: !Sub '${AWS::StackName}-DbEndpoint'
    Value: !GetAtt 'LakerunnerDb.Endpoint.Address'
  DbPort:
    Export:
      Name: !Sub '${AWS::StackName}-DbPort'
    Value: !GetAtt 'LakerunnerDb.Endpoint.Port'
  DbSecretArnOut:
    Export:
      Name: !Sub '${AWS::StackName}-DbSecretArn'
    Value: !Ref 'DbSecret'
  PrivateSubnetsOut:
    Export:
      Name: !Sub '${AWS::StackName}-PrivateSubnets'
    Value: !Sub
      - ${Subnet1},${Subnet2}
      - Subnet1: !Select
          - 0
          - !Ref 'PrivateSubnets'
        Subnet2: !Select
          - 1
          - !Ref 'PrivateSubnets'
  PublicSubnetsOut:
    Export:
      Name: !Sub '${AWS::StackName}-PublicSubnets'
    Value: !If
      - HasPublicSubnets
      - !Join
        - ','
        - !Ref 'PublicSubnets'
      - ''
  SupportsInternetFacingAlb:
    Description: Whether this CommonInfra stack supports internet-facing ALBs (requires PublicSubnets)
    Export:
      Name: !Sub '${AWS::StackName}-SupportsInternetFacingAlb'
    Value: !If
      - HasPublicSubnets
      - 'Yes'
      - 'No'
  TaskSecurityGroupId:
    Export:
      Name: !Sub '${AWS::StackName}-TaskSGId'
    Value: !Ref 'TaskSG'
  VpcIdOut:
    Export:
      Name: !Sub '${AWS::StackName}-VpcId'
    Value: !Ref 'VpcId'
Parameters:
  ApiKeysOverride:
    Default: ''
    Description: 'OPTIONAL: Custom API keys configuration in YAML format. Leave blank to use defaults from defaults.yaml. Example: - organization_id: xxx\n  keys:\n    - keyvalue'
    Type: String
  PrivateSubnets:
    Description: 'REQUIRED: Private subnet IDs (for RDS/ECS). Provide at least two in different AZs.'
    Type: List<AWS::EC2::Subnet::Id>
  PublicSubnets:
    Default: ''
    Description: Public subnet IDs (for internet-facing ALB). Required when ALB uses internet-facing scheme. Provide at least two in different AZs.
    Type: List<AWS::EC2::Subnet::Id>
  StorageProfilesOverride:
    Default: ''
    Description: 'OPTIONAL: Custom storage profiles configuration in YAML format. Leave blank to use defaults from defaults.yaml. Bucket name and region will be auto-filled.'
    Type: String
  VpcId:
    Description: 'REQUIRED: VPC where resources will be created.'
    Type: AWS::EC2::VPC::Id
Resources:
  ApiKeysParam:
    Properties:
      Description: API keys configuration
      Name: /lakerunner/api_keys
      Type: String
      Value: !If
        - HasApiKeysOverride
        - !Ref 'ApiKeysOverride'
        - "- keys:\n  - f70603aa00e6f67999cc66e336134887\n  organization_id: 12340000-0000-4000-8000-000000000000\n"
    Type: AWS::SSM::Parameter
  Cluster:
    Properties:
      ClusterName: !Sub '${AWS::StackName}-cluster'
    Type: AWS::ECS::Cluster
  DbSecret:
    Properties:
      GenerateSecretString:
        ExcludePunctuation: true
        GenerateStringKey: password
        SecretStringTemplate: '{"username":"lakerunner"}'
    Type: AWS::SecretsManager::Secret
  DbSubnetGroup:
    Properties:
      DBSubnetGroupDescription: DB subnets
      SubnetIds: !Ref 'PrivateSubnets'
    Type: AWS::RDS::DBSubnetGroup
  IngestBucket:
    DeletionPolicy: Delete
    Properties:
      LifecycleConfiguration:
        Rules:
          - ExpirationInDays: 10
            Prefix: otel-raw/
            Status: Enabled
      NotificationConfiguration:
        QueueConfigurations:
          - Event: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: otel-raw/
            Queue: !GetAtt 'IngestQueue.Arn'
          - Event: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: logs-raw/
            Queue: !GetAtt 'IngestQueue.Arn'
          - Event: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: metrics-raw/
            Queue: !GetAtt 'IngestQueue.Arn'
    Type: AWS::S3::Bucket
  IngestQueue:
    Properties:
      MessageRetentionPeriod: 345600
      QueueName: lakerunner-ingest-queue
    Type: AWS::SQS::Queue
  IngestQueuePolicy:
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - sqs:GetQueueAttributes
              - sqs:GetQueueUrl
              - sqs:SendMessage
            Condition:
              StringEquals:
                aws:SourceAccount: !Ref 'AWS::AccountId'
            Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Resource: !GetAtt 'IngestQueue.Arn'
        Version: '2012-10-17'
      Queues:
        - !Ref 'IngestQueue'
    Type: AWS::SQS::QueuePolicy
  LakerunnerDb:
    Properties:
      AllocatedStorage: '100'
      CopyTagsToSnapshot: true
      DBInstanceClass: db.t3.medium
      DBName: lakerunner
      DBSubnetGroupName: !Ref 'DbSubnetGroup'
      DeletionProtection: false
      Engine: postgres
      EngineVersion: '17'
      MasterUserPassword: !Sub
        - '{{resolve:secretsmanager:${S}:SecretString:password}}'
        - S: !Ref 'DbSecret'
      MasterUsername: !Sub
        - '{{resolve:secretsmanager:${S}:SecretString:username}}'
        - S: !Ref 'DbSecret'
      MultiAZ: false
      PubliclyAccessible: false
      StorageType: gp3
      VPCSecurityGroups:
        - !Ref 'TaskSG'
    Type: AWS::RDS::DBInstance
  StorageProfilesParam:
    Properties:
      Description: Storage profiles configuration
      Name: /lakerunner/storage_profiles
      Type: String
      Value: !If
        - HasStorageProfilesOverride
        - !Ref 'StorageProfilesOverride'
        - !Sub
          - "- bucket: ${Bucket}\n  cloud_provider: aws\n  collector_name: lakerunner\n  insecure_tls: false\n  instance_num: 1\n  organization_id: 12340000-0000-4000-8000-000000000000\n  region: ${AWS::Region}\n\
            \  use_path_style: true\n"
          - Bucket: !Ref 'IngestBucket'
    Type: AWS::SSM::Parameter
  TaskSG:
    Properties:
      GroupDescription: Security group for ECS tasks
      SecurityGroupEgress:
        - CidrIp: '0.0.0.0/0'
          Description: Allow all outbound
          IpProtocol: '-1'
      VpcId: !Ref 'VpcId'
    Type: AWS::EC2::SecurityGroup
  TaskSG7101Self:
    Properties:
      Description: task-to-task 7101
      FromPort: 7101
      GroupId: !Ref 'TaskSG'
      IpProtocol: tcp
      SourceSecurityGroupId: !Ref 'TaskSG'
      ToPort: 7101
    Type: AWS::EC2::SecurityGroupIngress
  TaskSGDbSelf:
    Properties:
      Description: task-to-database PostgreSQL
      FromPort: 5432
      GroupId: !Ref 'TaskSG'
      IpProtocol: tcp
      SourceSecurityGroupId: !Ref 'TaskSG'
      ToPort: 5432
    Type: AWS::EC2::SecurityGroupIngress

