Conditions:
  HasMcpApiKey: !Not
    - !Equals
      - !Ref 'McpApiKey'
      - ''
  IsInternetFacing: !Equals
    - !Ref 'AlbScheme'
    - internet-facing
Description: 'Lakerunner MCP Combined Service: MCP server with local-api for embeddings and LLM inference'
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Infrastructure
        Parameters:
          - CommonInfraStackName
          - QueryApiUrl
          - AlbScheme
      - Label:
          default: API Configuration
        Parameters:
          - LakerunnerApiKey
          - McpApiKey
      - Label:
          default: Container Images
        Parameters:
          - McpCombinedImage
    ParameterLabels:
      AlbScheme:
        default: ALB Scheme
      CommonInfraStackName:
        default: Common Infra Stack Name
      LakerunnerApiKey:
        default: Lakerunner API Key
      McpApiKey:
        default: MCP API Key (Optional)
      McpCombinedImage:
        default: MCP Combined Image
      QueryApiUrl:
        default: Query API URL
Outputs:
  BedrockModelsUsed:
    Description: >-
      List of AWS Bedrock models that the MCP combined service is configured to use: (1) us.anthropic.claude-sonnet-4-5-* for LLM inference, (2) amazon.titan-embed-text-v2:0 for embeddings. Ensure these
      models are enabled in your AWS account's Bedrock service in the deployment region.
    Value: claude-sonnet-4-5 (LLM), titan-embed-text-v2 (embeddings)
  BedrockPermissionsPolicy:
    Description: >-
      IAM policy document showing the Bedrock permissions already granted to the task role. The task role (TaskRoleArn output) has this policy attached. Use this as a reference if you need to grant the
      same permissions to other roles or users.
    Value: !Sub "{\n  \"Version\": \"2012-10-17\",\n  \"Statement\": [\n    {\n      \"Sid\": \"BedrockModelInvokeAccess\",\n      \"Effect\": \"Allow\",\n      \"Action\": [\n        \"bedrock:InvokeModel\"\
      ,\n        \"bedrock:InvokeModelWithResponseStream\"\n      ],\n      \"Resource\": [\n        \"arn:aws:bedrock:*::foundation-model/us.anthropic.claude-sonnet-4-5-*\",\n        \"arn:aws:bedrock:*::foundation-model/amazon.titan-embed-text-v2:0\"\
      \n      ]\n    }\n  ]\n}"
  LocalApiUrl:
    Description: URL to access local-api service
    Value: !Sub
      - http://${McpAlbDns}:20202
      - McpAlbDns: !GetAtt 'McpAlb.DNSName'
  McpAlbArn:
    Export:
      Name: !Sub '${AWS::StackName}-AlbArn'
    Value: !Ref 'McpAlb'
  McpAlbDNS:
    Export:
      Name: !Sub '${AWS::StackName}-AlbDNS'
    Value: !GetAtt 'McpAlb.DNSName'
  McpServiceArn:
    Export:
      Name: !Sub '${AWS::StackName}-ServiceArn'
    Value: !Ref 'McpService'
  McpUrl:
    Description: URL to access MCP server
    Value: !Sub
      - http://${McpAlbDns}:8080
      - McpAlbDns: !GetAtt 'McpAlb.DNSName'
  TaskRoleArn:
    Description: >-
      ARN of the ECS task role with Bedrock permissions. This role already has permissions for: (1) AWS Bedrock InvokeModel and InvokeModelWithResponseStream for Claude Sonnet 4.5 and Titan Embeddings v2,
      (2) CloudWatch Logs. If you need to grant additional permissions (e.g., S3, DynamoDB), attach policies to this role ARN. See the BedrockPermissionsPolicy output for the IAM policy document that grants
      Bedrock access.
    Export:
      Name: !Sub '${AWS::StackName}-TaskRoleArn'
    Value: !GetAtt 'McpTaskRole.Arn'
Parameters:
  AlbScheme:
    AllowedValues:
      - internet-facing
      - internal
    Default: internal
    Description: 'Load balancer scheme: ''internet-facing'' for external access or ''internal'' for internal access only.'
    Type: String
  CommonInfraStackName:
    Description: 'REQUIRED: Name of the CommonInfra stack to import infrastructure values from.'
    Type: String
  LakerunnerApiKey:
    Description: 'REQUIRED: API key for accessing the Lakerunner Query API'
    NoEcho: true
    Type: String
  McpApiKey:
    Default: ''
    Description: 'OPTIONAL: API key for MCP endpoint authentication. Leave blank to disable authentication.'
    NoEcho: true
    Type: String
  McpCombinedImage:
    Default: docker.flame.org/library/lakerunner-mcp-combined:latest
    Description: Container image for MCP combined service
    Type: String
  QueryApiUrl:
    Description: 'REQUIRED: Full URL to the Query API endpoint (e.g., http://alb-dns-name.region.elb.amazonaws.com:7101)'
    Type: String
Resources:
  LakerunnerApiKeySecret:
    Properties:
      Description: Lakerunner API key for MCP combined service
      Name: !Sub '${AWS::StackName}-lakerunner-api-key'
      SecretString: !Ref 'LakerunnerApiKey'
    Type: AWS::SecretsManager::Secret
  LocalApiListener:
    Properties:
      DefaultActions:
        - TargetGroupArn: !Ref 'LocalApiTg'
          Type: forward
      LoadBalancerArn: !Ref 'McpAlb'
      Port: '20202'
      Protocol: HTTP
    Type: AWS::ElasticLoadBalancingV2::Listener
  LocalApiTg:
    Properties:
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: /health
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      Matcher:
        HttpCode: '200'
      Port: 20202
      Protocol: HTTP
      TargetGroupAttributes:
        - Key: stickiness.enabled
          Value: 'false'
        - Key: deregistration_delay.timeout_seconds
          Value: '30'
      TargetType: ip
      UnhealthyThresholdCount: 3
      VpcId: !ImportValue
        Fn::Sub:
          - ${CommonInfraStackName}-VpcId
          - CommonInfraStackName: !Ref 'CommonInfraStackName'
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
  McpAlb:
    Properties:
      Scheme: !Ref 'AlbScheme'
      SecurityGroups:
        - !Ref 'McpAlbSecurityGroup'
      Subnets: !If
        - IsInternetFacing
        - !Split
          - ','
          - !ImportValue
            Fn::Sub:
              - ${CommonInfraStackName}-PublicSubnets
              - CommonInfraStackName: !Ref 'CommonInfraStackName'
        - !Split
          - ','
          - !ImportValue
            Fn::Sub:
              - ${CommonInfraStackName}-PrivateSubnets
              - CommonInfraStackName: !Ref 'CommonInfraStackName'
      Type: application
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
  McpAlb20202Open:
    Properties:
      CidrIp: '0.0.0.0/0'
      Description: HTTP 20202 for local-api
      FromPort: 20202
      GroupId: !Ref 'McpAlbSecurityGroup'
      IpProtocol: tcp
      ToPort: 20202
    Type: AWS::EC2::SecurityGroupIngress
  McpAlb8080Open:
    Properties:
      CidrIp: '0.0.0.0/0'
      Description: HTTP 8080 for MCP server
      FromPort: 8080
      GroupId: !Ref 'McpAlbSecurityGroup'
      IpProtocol: tcp
      ToPort: 8080
    Type: AWS::EC2::SecurityGroupIngress
  McpAlbSecurityGroup:
    Properties:
      GroupDescription: Security group for MCP Combined ALB
      SecurityGroupEgress:
        - CidrIp: '0.0.0.0/0'
          Description: Allow all outbound
          IpProtocol: '-1'
      VpcId: !ImportValue
        Fn::Sub:
          - ${CommonInfraStackName}-VpcId
          - CommonInfraStackName: !Ref 'CommonInfraStackName'
    Type: AWS::EC2::SecurityGroup
  McpApiKeySecret:
    Condition: HasMcpApiKey
    Properties:
      Description: MCP API key for endpoint authentication
      Name: !Sub '${AWS::StackName}-mcp-api-key'
      SecretString: !Ref 'McpApiKey'
    Type: AWS::SecretsManager::Secret
  McpExecRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
        Version: '2012-10-17'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                  - secretsmanager:GetSecretValue
                Effect: Allow
                Resource:
                  - !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${AWS::StackName}-*'
              - Action:
                  - ssmmessages:CreateControlChannel
                  - ssmmessages:CreateDataChannel
                  - ssmmessages:OpenControlChannel
                  - ssmmessages:OpenDataChannel
                Effect: Allow
                Resource: '*'
            Version: '2012-10-17'
          PolicyName: SecretsAccess
      RoleName: !Sub '${AWS::StackName}-exec-role'
    Type: AWS::IAM::Role
  McpListener:
    Properties:
      DefaultActions:
        - TargetGroupArn: !Ref 'McpTg'
          Type: forward
      LoadBalancerArn: !Ref 'McpAlb'
      Port: '8080'
      Protocol: HTTP
    Type: AWS::ElasticLoadBalancingV2::Listener
  McpLogGroup:
    Properties:
      LogGroupName: !Sub '/ecs/mcp-combined'
      RetentionInDays: 14
    Type: AWS::Logs::LogGroup
  McpService:
    DependsOn:
      - McpListener
      - LocalApiListener
    Properties:
      Cluster: !ImportValue
        Fn::Sub:
          - ${CommonInfraStackName}-ClusterArn
          - CommonInfraStackName: !Ref 'CommonInfraStackName'
      DesiredCount: '2'
      EnableECSManagedTags: true
      EnableExecuteCommand: true
      LaunchType: FARGATE
      LoadBalancers:
        - ContainerName: McpCombinedContainer
          ContainerPort: 8080
          TargetGroupArn: !Ref 'McpTg'
        - ContainerName: McpCombinedContainer
          ContainerPort: 20202
          TargetGroupArn: !Ref 'LocalApiTg'
      NetworkConfiguration:
        AwsvpcConfiguration:
          SecurityGroups:
            - !ImportValue
              Fn::Sub:
                - ${CommonInfraStackName}-TaskSGId
                - CommonInfraStackName: !Ref 'CommonInfraStackName'
          Subnets: !Split
            - ','
            - !ImportValue
              Fn::Sub:
                - ${CommonInfraStackName}-PrivateSubnets
                - CommonInfraStackName: !Ref 'CommonInfraStackName'
      PropagateTags: SERVICE
      ServiceName: mcp-combined
      Tags:
        - Key: Component
          Value: Service
        - Key: Environment
          Value: !Ref 'AWS::StackName'
        - Key: ManagedBy
          Value: Lakerunner
        - Key: Name
          Value: !Sub '${AWS::StackName}-mcp-combined'
      TaskDefinition: !Ref 'McpTaskDef'
    Type: AWS::ECS::Service
  McpTaskDef:
    Properties:
      ContainerDefinitions:
        - Environment:
            - Name: BUMP_REVISION
              Value: '1'
            - Name: OTEL_SERVICE_NAME
              Value: mcp-combined
            - Name: TMPDIR
              Value: /scratch
            - Name: HOME
              Value: /scratch
            - Name: LAKERUNNER_API_URL
              Value: !Ref 'QueryApiUrl'
            - Name: MCP_HOST
              Value: '0.0.0.0'
            - Name: MCP_TRANSPORT
              Value: http
            - Name: LAKERUNNER_STREAM_ATTRIBUTE
              Value: resource_service_name
            - Name: WORKING_DIRECTORY
              Value: /app/workdir
            - Name: GIN_MODE
              Value: release
            - Name: AWS_REGION
              Value: us-east-1
            - Name: MCP_PORT
              Value: '8080'
            - Name: PORT
              Value: '20202'
          HealthCheck:
            Command:
              - CMD-SHELL
              - wget --no-verbose --tries=1 --spider http://localhost:8080/health || exit 1
            Interval: 30
            Retries: 3
            StartPeriod: 30
            Timeout: 5
          Image: !Ref 'McpCombinedImage'
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref 'McpLogGroup'
              awslogs-region: !Ref 'AWS::Region'
              awslogs-stream-prefix: mcp-combined
          Name: McpCombinedContainer
          PortMappings:
            - ContainerPort: 8080
              Protocol: tcp
            - ContainerPort: 20202
              Protocol: tcp
          Secrets:
            - Name: LAKERUNNER_API_KEY
              ValueFrom: !Ref 'LakerunnerApiKeySecret'
          User: '65532'
      Cpu: '512'
      ExecutionRoleArn: !GetAtt 'McpExecRole.Arn'
      Family: mcp-combined-task
      Memory: '1024'
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      RuntimePlatform:
        CpuArchitecture: ARM64
        OperatingSystemFamily: LINUX
      TaskRoleArn: !GetAtt 'McpTaskRole.Arn'
      Volumes:
        - Name: scratch
    Type: AWS::ECS::TaskDefinition
  McpTaskRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
        Version: '2012-10-17'
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Effect: Allow
                Resource: '*'
            Version: '2012-10-17'
          PolicyName: LogAccess
        - PolicyDocument:
            Statement:
              - Action:
                  - bedrock:InvokeModel
                  - bedrock:InvokeModelWithResponseStream
                Effect: Allow
                Resource:
                  - arn:aws:bedrock:*::foundation-model/us.anthropic.claude-sonnet-4-5-*
                  - arn:aws:bedrock:*::foundation-model/amazon.titan-embed-text-v2:0
            Version: '2012-10-17'
          PolicyName: BedrockAccess
      RoleName: !Sub '${AWS::StackName}-task-role'
    Type: AWS::IAM::Role
  McpTg:
    Properties:
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: /health
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      Matcher:
        HttpCode: '200'
      Port: 8080
      Protocol: HTTP
      TargetGroupAttributes:
        - Key: stickiness.enabled
          Value: 'false'
        - Key: deregistration_delay.timeout_seconds
          Value: '30'
      TargetType: ip
      UnhealthyThresholdCount: 3
      VpcId: !ImportValue
        Fn::Sub:
          - ${CommonInfraStackName}-VpcId
          - CommonInfraStackName: !Ref 'CommonInfraStackName'
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
  TaskFromMcpAlb20202:
    Properties:
      Description: MCP ALB to tasks 20202
      FromPort: 20202
      GroupId: !ImportValue
        Fn::Sub:
          - ${CommonInfraStackName}-TaskSGId
          - CommonInfraStackName: !Ref 'CommonInfraStackName'
      IpProtocol: tcp
      SourceSecurityGroupId: !Ref 'McpAlbSecurityGroup'
      ToPort: 20202
    Type: AWS::EC2::SecurityGroupIngress
  TaskFromMcpAlb8080:
    Properties:
      Description: MCP ALB to tasks 8080
      FromPort: 8080
      GroupId: !ImportValue
        Fn::Sub:
          - ${CommonInfraStackName}-TaskSGId
          - CommonInfraStackName: !Ref 'CommonInfraStackName'
      IpProtocol: tcp
      SourceSecurityGroupId: !Ref 'McpAlbSecurityGroup'
      ToPort: 8080
    Type: AWS::EC2::SecurityGroupIngress

